// Generated by scripts/gen_mock_girocodes.py from the real gate — do not edit by hand.
import type { GiroCode, GiroCodeBlocked, GiroCodeReady } from "@/api/types";

/** Each payment's GiroCode as the demo starts (or why there is none). */
export const GIROCODES: Record<string, GiroCode> = {
  "itm_parking": {
    "status": "blocked",
    "item_id": "itm_parking",
    "reason": "check_letter",
    "message": "No code yet: the amount, the IBAN and the reference were read by AI from a photo. Compare them with the paper letter, then confirm.",
    "to_check": [
      "amount",
      "iban",
      "reference"
    ],
    "values": {
      "payee": "Stadtkasse Musterstadt",
      "iban": "DE51123456000000100017",
      "reference": "OA-VW-2026-55012",
      "amount": 30.0
    }
  },
  "itm_tm_dunning": {
    "status": "ready",
    "item_id": "itm_tm_dunning",
    "payload": "BCD\n002\n1\nSCT\n\nTechMarkt Online GmbH\nDE70123478000048213000\nEUR94.99\n\n\nRE-2026-084213",
    "checked": false
  },
  "itm_tm_invoice": {
    "status": "blocked",
    "item_id": "itm_tm_invoice",
    "reason": "settled",
    "message": "No code: you set this to-do aside.",
    "to_check": [],
    "values": null
  },
  "itm_rent_oct": {
    "status": "blocked",
    "item_id": "itm_rent_oct",
    "reason": "several",
    "message": "No code: this letter asks for more than one payment, and its reference may belong to only one of them. Copy the details by hand.",
    "to_check": [],
    "values": null
  },
  "itm_rent_sep": {
    "status": "blocked",
    "item_id": "itm_rent_sep",
    "reason": "settled",
    "message": "No code: you marked this as paid.",
    "to_check": [],
    "values": null
  },
  "itm_nk": {
    "status": "ready",
    "item_id": "itm_nk",
    "payload": "BCD\n002\n1\nSCT\n\nWohnbau Musterstadt eG\nDE05123456000004455660\nEUR184.3\n\n\nMV-2025-0412 NK 2025",
    "checked": false
  },
  "itm_rundfunk": {
    "status": "ready",
    "item_id": "itm_rundfunk",
    "payload": "BCD\n002\n1\nSCT\n\nBeitragsservice Musterstadt\nDE57123489000055081836\nEUR55.08\n\n\n457 812 309",
    "checked": false
  },
  "itm_semester": {
    "status": "ready",
    "item_id": "itm_semester",
    "payload": "BCD\n002\n1\nSCT\n\nHochschule Musterstadt\nDE10123456000007700220\nEUR312.4\n\n\n2231847 SoSe27",
    "checked": false
  },
  "itm_scam_demand": {
    "status": "blocked",
    "item_id": "itm_scam_demand",
    "reason": "scam",
    "message": "No code: this IBAN is not the one Beitragsservice Musterstadt used before. Check with them using contact details you already have, not the ones in this letter.",
    "to_check": [],
    "values": null
  },
  "itm_library_fee": {
    "status": "blocked",
    "item_id": "itm_library_fee",
    "reason": "no_iban",
    "message": "No code: the letter gives no IBAN to transfer to.",
    "to_check": [],
    "values": null
  },
  "itm_abh_fee": {
    "status": "blocked",
    "item_id": "itm_abh_fee",
    "reason": "no_iban",
    "message": "No code: the letter gives no IBAN to transfer to.",
    "to_check": [],
    "values": null
  },
  "itm_power_abschlag": {
    "status": "blocked",
    "item_id": "itm_power_abschlag",
    "reason": "no_iban",
    "message": "No code: the letter gives no IBAN to transfer to.",
    "to_check": [],
    "values": null
  },
  "itm_bkk": {
    "status": "blocked",
    "item_id": "itm_bkk",
    "reason": "no_iban",
    "message": "No code: the letter gives no IBAN to transfer to.",
    "to_check": [],
    "values": null
  },
  "itm_liability": {
    "status": "blocked",
    "item_id": "itm_liability",
    "reason": "no_iban",
    "message": "No code: the letter gives no IBAN to transfer to.",
    "to_check": [],
    "values": null
  },
  "itm_power_new": {
    "status": "blocked",
    "item_id": "itm_power_new",
    "reason": "no_iban",
    "message": "No code: the letter gives no IBAN to transfer to.",
    "to_check": [],
    "values": null
  }
};

/** The code once the person compared the details with the paper letter. */
export const GIROCODES_CHECKED: Record<string, GiroCodeReady> = {
  "itm_parking": {
    "status": "ready",
    "item_id": "itm_parking",
    "payload": "BCD\n002\n1\nSCT\n\nStadtkasse Musterstadt\nDE51123456000000100017\nEUR30\n\n\nOA-VW-2026-55012",
    "checked": true
  }
};

/**
 * What a payment with a code (or waiting for one) asks once its amount was changed by hand: compare
 * with the paper letter (`values.amount` is the to-do's new amount, filled in by the mock).
 */
export const GIROCODES_AMOUNT_CHANGED: Record<string, GiroCodeBlocked> = {
  "itm_parking": {
    "status": "blocked",
    "item_id": "itm_parking",
    "reason": "check_letter",
    "message": "No code yet: the amount, the IBAN and the reference were read by AI from a photo. Compare them with the paper letter, then confirm.",
    "to_check": [
      "amount",
      "iban",
      "reference"
    ],
    "values": {
      "payee": "Stadtkasse Musterstadt",
      "iban": "DE51123456000000100017",
      "reference": "OA-VW-2026-55012",
      "amount": null
    }
  },
  "itm_tm_dunning": {
    "status": "blocked",
    "item_id": "itm_tm_dunning",
    "reason": "check_letter",
    "message": "No code yet: the amount wasn't found in the letter's text. Compare it with the paper letter, then confirm.",
    "to_check": [
      "amount"
    ],
    "values": {
      "payee": "TechMarkt Online GmbH",
      "iban": "DE70123478000048213000",
      "reference": "RE-2026-084213",
      "amount": null
    }
  },
  "itm_nk": {
    "status": "blocked",
    "item_id": "itm_nk",
    "reason": "check_letter",
    "message": "No code yet: the amount wasn't found in the letter's text. Compare it with the paper letter, then confirm.",
    "to_check": [
      "amount"
    ],
    "values": {
      "payee": "Wohnbau Musterstadt eG",
      "iban": "DE05123456000004455660",
      "reference": "MV-2025-0412 NK 2025",
      "amount": null
    }
  },
  "itm_rundfunk": {
    "status": "blocked",
    "item_id": "itm_rundfunk",
    "reason": "check_letter",
    "message": "No code yet: the amount wasn't found in the letter's text. Compare it with the paper letter, then confirm.",
    "to_check": [
      "amount"
    ],
    "values": {
      "payee": "Beitragsservice Musterstadt",
      "iban": "DE57123489000055081836",
      "reference": "457 812 309",
      "amount": null
    }
  },
  "itm_semester": {
    "status": "blocked",
    "item_id": "itm_semester",
    "reason": "check_letter",
    "message": "No code yet: the amount wasn't found in the letter's text. Compare it with the paper letter, then confirm.",
    "to_check": [
      "amount"
    ],
    "values": {
      "payee": "Hochschule Musterstadt",
      "iban": "DE10123456000007700220",
      "reference": "2231847 SoSe27",
      "amount": null
    }
  }
};

/** Why a payment marked paid or set aside, or without an account or an amount, has no code. */
export const GIROCODE_MESSAGES: Record<"done" | "dismissed" | "no_iban" | "no_amount", string> = {
  "done": "No code: you marked this as paid.",
  "dismissed": "No code: you set this to-do aside.",
  "no_iban": "No code: the letter gives no IBAN to transfer to.",
  "no_amount": "No code: the letter doesn't say how much to pay."
};

/** Why “These match the letter” is refused (409). */
export const GIROCODE_REFUSALS = {
  "not_a_payment": "This to-do isn't a payment from a letter.",
  "nothing_to_compare": "There is nothing to compare for this payment.",
  "changed": "The payment details changed since you looked at them. Please compare them again."
} as const;
