// Generated by scripts/gen_mock_high_stakes.py from the real rules — do not edit by hand.
import type { ComputationReceipt, DateSpec, Priority, SendGuidance } from "@/api/types";

/** The Mahnbescheid's objection deadline: unknown envelope date, and each date Sam may enter. */
export const ORDER_RECEIPTS: Record<string, ComputationReceipt> = {
  "unknown": {
    "due_date": "2026-10-07",
    "send_by": "2026-10-01",
    "safe_date": null,
    "holiday_calendar": "Nordrhein-Westfalen",
    "summary": "Two weeks after the letter's date (Wed 23 Sep 2026) is Wed 7 Oct 2026.",
    "steps": [
      {
        "label": "Counting starts the day after Wed 23 Sep 2026",
        "date": "2026-09-23",
        "rule_id": "bgb_187_1",
        "citation": "§ 222 Abs. 1 ZPO; § 187 Abs. 1 BGB"
      },
      {
        "label": "Two weeks later: Wed 7 Oct 2026",
        "date": "2026-10-07",
        "rule_id": "bgb_188",
        "citation": "§ 222 Abs. 1 ZPO; § 188 Abs. 1, 2 BGB"
      },
      {
        "label": "Wed 7 Oct 2026 is a working day, so it stays",
        "date": "2026-10-07",
        "rule_id": "zpo_222",
        "citation": "§ 222 Abs. 1, 2 ZPO"
      },
      {
        "label": "Send by Thu 1 Oct 2026 to allow 4 business days for a letter to arrive",
        "date": "2026-10-01",
        "rule_id": "postal_buffer",
        "citation": "Ordnung safety policy; § 18 PostG (delivery targets)"
      }
    ],
    "rule_ids": [
      "zpo_692",
      "bgb_187_1",
      "bgb_188",
      "zpo_180",
      "zpo_222",
      "postal_buffer"
    ],
    "warnings": [
      "This is a court deadline. Ordnung's date is information, not legal advice — if you don't owe the money, object in time and get advice (see the card on this letter).",
      "A late objection still counts until the enforcement order is issued (§ 694 ZPO) — but don't rely on that.",
      "We assumed the letter was delivered on the date printed on it — tell us the delivery date the postman wrote on the yellow envelope."
    ],
    "confidence": "low"
  },
  "2026-09-23": {
    "due_date": "2026-10-07",
    "send_by": "2026-10-01",
    "safe_date": null,
    "holiday_calendar": "Nordrhein-Westfalen",
    "summary": "Two weeks after the day it was delivered (Wed 23 Sep 2026) is Wed 7 Oct 2026.",
    "steps": [
      {
        "label": "Counting starts the day after Wed 23 Sep 2026",
        "date": "2026-09-23",
        "rule_id": "bgb_187_1",
        "citation": "§ 222 Abs. 1 ZPO; § 187 Abs. 1 BGB"
      },
      {
        "label": "Two weeks later: Wed 7 Oct 2026",
        "date": "2026-10-07",
        "rule_id": "bgb_188",
        "citation": "§ 222 Abs. 1 ZPO; § 188 Abs. 1, 2 BGB"
      },
      {
        "label": "Wed 7 Oct 2026 is a working day, so it stays",
        "date": "2026-10-07",
        "rule_id": "zpo_222",
        "citation": "§ 222 Abs. 1, 2 ZPO"
      },
      {
        "label": "Send by Thu 1 Oct 2026 to allow 4 business days for a letter to arrive",
        "date": "2026-10-01",
        "rule_id": "postal_buffer",
        "citation": "Ordnung safety policy; § 18 PostG (delivery targets)"
      }
    ],
    "rule_ids": [
      "zpo_692",
      "bgb_187_1",
      "bgb_188",
      "zpo_180",
      "zpo_222",
      "postal_buffer"
    ],
    "warnings": [
      "This is a court deadline. Ordnung's date is information, not legal advice — if you don't owe the money, object in time and get advice (see the card on this letter).",
      "A late objection still counts until the enforcement order is issued (§ 694 ZPO) — but don't rely on that."
    ],
    "confidence": "medium"
  },
  "2026-09-24": {
    "due_date": "2026-10-08",
    "send_by": "2026-10-02",
    "safe_date": null,
    "holiday_calendar": "Nordrhein-Westfalen",
    "summary": "Two weeks after the day it was delivered (Thu 24 Sep 2026) is Thu 8 Oct 2026.",
    "steps": [
      {
        "label": "Counting starts the day after Thu 24 Sep 2026",
        "date": "2026-09-24",
        "rule_id": "bgb_187_1",
        "citation": "§ 222 Abs. 1 ZPO; § 187 Abs. 1 BGB"
      },
      {
        "label": "Two weeks later: Thu 8 Oct 2026",
        "date": "2026-10-08",
        "rule_id": "bgb_188",
        "citation": "§ 222 Abs. 1 ZPO; § 188 Abs. 1, 2 BGB"
      },
      {
        "label": "Thu 8 Oct 2026 is a working day, so it stays",
        "date": "2026-10-08",
        "rule_id": "zpo_222",
        "citation": "§ 222 Abs. 1, 2 ZPO"
      },
      {
        "label": "Send by Fri 2 Oct 2026 to allow 4 business days for a letter to arrive",
        "date": "2026-10-02",
        "rule_id": "postal_buffer",
        "citation": "Ordnung safety policy; § 18 PostG (delivery targets)"
      }
    ],
    "rule_ids": [
      "zpo_692",
      "bgb_187_1",
      "bgb_188",
      "zpo_180",
      "zpo_222",
      "postal_buffer"
    ],
    "warnings": [
      "This is a court deadline. Ordnung's date is information, not legal advice — if you don't owe the money, object in time and get advice (see the card on this letter).",
      "A late objection still counts until the enforcement order is issued (§ 694 ZPO) — but don't rely on that."
    ],
    "confidence": "medium"
  },
  "2026-09-25": {
    "due_date": "2026-10-09",
    "send_by": "2026-10-05",
    "safe_date": null,
    "holiday_calendar": "Nordrhein-Westfalen",
    "summary": "Two weeks after the day it was delivered (Fri 25 Sep 2026) is Fri 9 Oct 2026.",
    "steps": [
      {
        "label": "Counting starts the day after Fri 25 Sep 2026",
        "date": "2026-09-25",
        "rule_id": "bgb_187_1",
        "citation": "§ 222 Abs. 1 ZPO; § 187 Abs. 1 BGB"
      },
      {
        "label": "Two weeks later: Fri 9 Oct 2026",
        "date": "2026-10-09",
        "rule_id": "bgb_188",
        "citation": "§ 222 Abs. 1 ZPO; § 188 Abs. 1, 2 BGB"
      },
      {
        "label": "Fri 9 Oct 2026 is a working day, so it stays",
        "date": "2026-10-09",
        "rule_id": "zpo_222",
        "citation": "§ 222 Abs. 1, 2 ZPO"
      },
      {
        "label": "Send by Mon 5 Oct 2026 to allow 4 business days for a letter to arrive",
        "date": "2026-10-05",
        "rule_id": "postal_buffer",
        "citation": "Ordnung safety policy; § 18 PostG (delivery targets)"
      }
    ],
    "rule_ids": [
      "zpo_692",
      "bgb_187_1",
      "bgb_188",
      "zpo_180",
      "zpo_222",
      "postal_buffer"
    ],
    "warnings": [
      "This is a court deadline. Ordnung's date is information, not legal advice — if you don't owe the money, object in time and get advice (see the card on this letter).",
      "A late objection still counts until the enforcement order is issued (§ 694 ZPO) — but don't rely on that."
    ],
    "confidence": "medium"
  },
  "2026-09-26": {
    "due_date": "2026-10-12",
    "send_by": "2026-10-06",
    "safe_date": null,
    "holiday_calendar": "Nordrhein-Westfalen",
    "summary": "Two weeks after the day it was delivered (Sat 26 Sep 2026) is Sat 10 Oct 2026, a Saturday, so the deadline moves to Mon 12 Oct 2026.",
    "steps": [
      {
        "label": "Counting starts the day after Sat 26 Sep 2026",
        "date": "2026-09-26",
        "rule_id": "bgb_187_1",
        "citation": "§ 222 Abs. 1 ZPO; § 187 Abs. 1 BGB"
      },
      {
        "label": "Two weeks later: Sat 10 Oct 2026",
        "date": "2026-10-10",
        "rule_id": "bgb_188",
        "citation": "§ 222 Abs. 1 ZPO; § 188 Abs. 1, 2 BGB"
      },
      {
        "label": "Sat 10 Oct 2026 is a Saturday, so the deadline moves to Mon 12 Oct 2026",
        "date": "2026-10-12",
        "rule_id": "zpo_222",
        "citation": "§ 222 Abs. 1, 2 ZPO"
      },
      {
        "label": "Send by Tue 6 Oct 2026 to allow 4 business days for a letter to arrive",
        "date": "2026-10-06",
        "rule_id": "postal_buffer",
        "citation": "Ordnung safety policy; § 18 PostG (delivery targets)"
      }
    ],
    "rule_ids": [
      "zpo_692",
      "bgb_187_1",
      "bgb_188",
      "zpo_180",
      "zpo_222",
      "postal_buffer"
    ],
    "warnings": [
      "This is a court deadline. Ordnung's date is information, not legal advice — if you don't owe the money, object in time and get advice (see the card on this letter).",
      "A late objection still counts until the enforcement order is issued (§ 694 ZPO) — but don't rely on that."
    ],
    "confidence": "medium"
  },
  "2026-09-27": {
    "due_date": "2026-10-12",
    "send_by": "2026-10-06",
    "safe_date": null,
    "holiday_calendar": "Nordrhein-Westfalen",
    "summary": "Two weeks after the day it was delivered (Sun 27 Sep 2026) is Sun 11 Oct 2026, a Sunday, so the deadline moves to Mon 12 Oct 2026.",
    "steps": [
      {
        "label": "Counting starts the day after Sun 27 Sep 2026",
        "date": "2026-09-27",
        "rule_id": "bgb_187_1",
        "citation": "§ 222 Abs. 1 ZPO; § 187 Abs. 1 BGB"
      },
      {
        "label": "Two weeks later: Sun 11 Oct 2026",
        "date": "2026-10-11",
        "rule_id": "bgb_188",
        "citation": "§ 222 Abs. 1 ZPO; § 188 Abs. 1, 2 BGB"
      },
      {
        "label": "Sun 11 Oct 2026 is a Sunday, so the deadline moves to Mon 12 Oct 2026",
        "date": "2026-10-12",
        "rule_id": "zpo_222",
        "citation": "§ 222 Abs. 1, 2 ZPO"
      },
      {
        "label": "Send by Tue 6 Oct 2026 to allow 4 business days for a letter to arrive",
        "date": "2026-10-06",
        "rule_id": "postal_buffer",
        "citation": "Ordnung safety policy; § 18 PostG (delivery targets)"
      }
    ],
    "rule_ids": [
      "zpo_692",
      "bgb_187_1",
      "bgb_188",
      "zpo_180",
      "zpo_222",
      "postal_buffer"
    ],
    "warnings": [
      "This is a court deadline. Ordnung's date is information, not legal advice — if you don't owe the money, object in time and get advice (see the card on this letter).",
      "A late objection still counts until the enforcement order is issued (§ 694 ZPO) — but don't rely on that."
    ],
    "confidence": "medium"
  },
  "2026-09-28": {
    "due_date": "2026-10-12",
    "send_by": "2026-10-06",
    "safe_date": null,
    "holiday_calendar": "Nordrhein-Westfalen",
    "summary": "Two weeks after the day it was delivered (Mon 28 Sep 2026) is Mon 12 Oct 2026.",
    "steps": [
      {
        "label": "Counting starts the day after Mon 28 Sep 2026",
        "date": "2026-09-28",
        "rule_id": "bgb_187_1",
        "citation": "§ 222 Abs. 1 ZPO; § 187 Abs. 1 BGB"
      },
      {
        "label": "Two weeks later: Mon 12 Oct 2026",
        "date": "2026-10-12",
        "rule_id": "bgb_188",
        "citation": "§ 222 Abs. 1 ZPO; § 188 Abs. 1, 2 BGB"
      },
      {
        "label": "Mon 12 Oct 2026 is a working day, so it stays",
        "date": "2026-10-12",
        "rule_id": "zpo_222",
        "citation": "§ 222 Abs. 1, 2 ZPO"
      },
      {
        "label": "Send by Tue 6 Oct 2026 to allow 4 business days for a letter to arrive",
        "date": "2026-10-06",
        "rule_id": "postal_buffer",
        "citation": "Ordnung safety policy; § 18 PostG (delivery targets)"
      }
    ],
    "rule_ids": [
      "zpo_692",
      "bgb_187_1",
      "bgb_188",
      "zpo_180",
      "zpo_222",
      "postal_buffer"
    ],
    "warnings": [
      "This is a court deadline. Ordnung's date is information, not legal advice — if you don't owe the money, object in time and get advice (see the card on this letter).",
      "A late objection still counts until the enforcement order is issued (§ 694 ZPO) — but don't rely on that."
    ],
    "confidence": "medium"
  }
};

/** The deadlines the law adds to the dismissal (to-dos with origin "rule"). */
export const DISMISSAL_RULES: Record<string, { spec: DateSpec; receipt: ComputationReceipt; title: string; action: string; consequence: string; priority: Priority }> = {
  "kschg_4": {
    "spec": {
      "type": "relative",
      "date": null,
      "time": null,
      "anchor": "receipt",
      "anchor_date": null,
      "amount": 3,
      "unit": "weeks",
      "delivery_rule": "none",
      "shift_rule": "auto",
      "nature": "objection",
      "legal_basis": "§ 4 S. 1 KSchG",
      "text": "innerhalb von drei Wochen nach Zugang der Kündigung"
    },
    "receipt": {
      "due_date": "2026-10-19",
      "send_by": "2026-10-13",
      "safe_date": null,
      "holiday_calendar": "Germany (nationwide holidays only)",
      "summary": "Three weeks after the day you received it (Mon 28 Sep 2026) is Mon 19 Oct 2026.",
      "steps": [
        {
          "label": "Counting starts the day after Mon 28 Sep 2026",
          "date": "2026-09-28",
          "rule_id": "bgb_187_1",
          "citation": "§ 187 Abs. 1 BGB"
        },
        {
          "label": "Three weeks later: Mon 19 Oct 2026",
          "date": "2026-10-19",
          "rule_id": "bgb_188",
          "citation": "§ 188 Abs. 1, 2 BGB"
        },
        {
          "label": "Mon 19 Oct 2026 is a working day, so it stays",
          "date": "2026-10-19",
          "rule_id": "bgb_193",
          "citation": "§ 193 BGB"
        },
        {
          "label": "Send by Tue 13 Oct 2026 to allow 4 business days for a letter to arrive",
          "date": "2026-10-13",
          "rule_id": "postal_buffer",
          "citation": "Ordnung safety policy; § 18 PostG (delivery targets)"
        }
      ],
      "rule_ids": [
        "kschg_4",
        "bgb_187_1",
        "bgb_188",
        "bgb_193",
        "postal_buffer"
      ],
      "warnings": [
        "This is the deadline for a court action at the labour court (Kündigungsschutzklage). Ordnung can't draft or file it — get advice now from a union, an employment lawyer or the court's Rechtsantragstelle."
      ],
      "confidence": "medium"
    },
    "title": "Get advice now: court action against the dismissal (Kündigungsschutzklage)",
    "action": "If you think the dismissal is wrong, talk to your union, an employment lawyer or the labour court's Rechtsantragstelle today. Only a court action filed in time keeps your rights.",
    "consequence": "If no court action reaches the labour court in time, the dismissal counts as valid (§ 7 KSchG).",
    "priority": "critical"
  },
  "sgb3_38": {
    "spec": {
      "type": "relative",
      "date": null,
      "time": null,
      "anchor": "receipt",
      "anchor_date": null,
      "amount": 3,
      "unit": "days",
      "delivery_rule": "none",
      "shift_rule": "auto",
      "nature": "declaration",
      "legal_basis": "§ 38 Abs. 1 SGB III",
      "text": "arbeitsuchend melden"
    },
    "receipt": {
      "due_date": "2026-10-01",
      "send_by": null,
      "safe_date": null,
      "holiday_calendar": "Germany (nationwide holidays only)",
      "summary": "Register as job-seeking by Thu 1 Oct 2026: three days after you learned the end date (Mon 28 Sep 2026).",
      "steps": [
        {
          "label": "You learned when the job ends on Mon 28 Sep 2026",
          "date": "2026-09-28",
          "rule_id": "sgb3_38",
          "citation": "§ 38 Abs. 1 SGB III; § 159 Abs. 1 S. 2 Nr. 9, Abs. 6 SGB III"
        },
        {
          "label": "As less than three months are left, register within three days: by Thu 1 Oct 2026",
          "date": "2026-10-01",
          "rule_id": "sgb3_38",
          "citation": "§ 38 Abs. 1 SGB III; § 159 Abs. 1 S. 2 Nr. 9, Abs. 6 SGB III"
        },
        {
          "label": "Register online, by phone or in person — it counts the day you do it",
          "date": "2026-10-01",
          "rule_id": "sgb3_38",
          "citation": "§ 38 Abs. 1 SGB III; § 159 Abs. 1 S. 2 Nr. 9, Abs. 6 SGB III"
        }
      ],
      "rule_ids": [
        "sgb3_38"
      ],
      "warnings": [],
      "confidence": "high"
    },
    "title": "Register as job-seeking (arbeitsuchend) at the Agentur für Arbeit",
    "action": "Register online, by phone or in person. Your details and the end date of the job are enough for now. Not needed if this ends an apprenticeship in a company (§ 38 Abs. 1 S. 4 SGB III). Working students (Werkstudenten) and mini-jobbers are usually not insured against unemployment (§ 27 SGB III): they have no benefit to lose, but registering still helps.",
    "consequence": "If you claim unemployment benefit, registering late can cost you one week of it (Sperrzeit).",
    "priority": "high"
  }
};

/** How to send the objection the law gives a court order or a landlord's notice (dates added per letter). */
export const STATUTORY_OBJECTIONS: Record<string, { guidance: SendGuidance; notes: string[] }> = {
  "court_payment_order": {
    "guidance": {
      "send_by": null,
      "must_arrive_by": null,
      "post_too_late": false,
      "form": "written_form",
      "form_note": "In writing to the court that issued the order (§ 694 ZPO) — best on the form that came with it (tick how much you object to and sign it), or online. No reasons are needed; e-mail is not valid.",
      "channels": [
        {
          "channel": "registered_letter",
          "label": "Signed form or letter by Einwurf-Einschreiben",
          "allowed": true,
          "recommended": true,
          "note": "Send it to the court that issued the order. Einwurf-Einschreiben (registered letter): keep the posting receipt and ask for the delivery record (Auslieferungsbeleg) — online tracking alone is no proof (BAG 2 AZR 68/24).",
          "citation": null
        },
        {
          "channel": "portal",
          "label": "online-mahnantrag.de",
          "allowed": true,
          "recommended": false,
          "note": "The courts' own site: object online with your ID card, or print a barcode form to sign and post.",
          "citation": null
        },
        {
          "channel": "in_person",
          "label": "Rechtsantragstelle (for the record)",
          "allowed": true,
          "recommended": false,
          "note": "Free: they write it down for you (zu Protokoll); bring the order and its envelope. At the court that issued the order it counts at once. Any other Amtsgericht can take it down too, but then it only counts once their record reaches the issuing court — go by the send-by date, as for a letter.",
          "citation": "§ 129a Abs. 1, 3 ZPO"
        },
        {
          "channel": "fax",
          "label": "Fax of the signed letter",
          "allowed": true,
          "recommended": false,
          "note": "Counts as written; keep the transmission report.",
          "citation": null
        },
        {
          "channel": "letter",
          "label": "Signed letter by normal post",
          "allowed": true,
          "recommended": false,
          "note": "Works, but you can't prove it arrived.",
          "citation": null
        },
        {
          "channel": "email",
          "label": "E-mail",
          "allowed": false,
          "recommended": false,
          "note": "Not valid at a court.",
          "citation": null
        }
      ],
      "tips": [
        "Keep a copy of the form you send and the envelope with the delivery date.",
        "Keep a copy of what you send and any proof of delivery."
      ]
    },
    "notes": [
      "In writing to the court that issued the order (§ 694 ZPO) — best on the form that came with it (tick how much you object to and sign it), or online. No reasons are needed; e-mail is not valid.",
      "This letter objects to the whole claim; no reasons are needed. To object to only part of it (for example only the interest or the costs), don't send this letter: use the form that came with the order and tick how much you object to, or go to the court's Rechtsantragstelle. Send the form or this letter, not both. Get advice if you're unsure."
    ]
  },
  "enforcement_order": {
    "guidance": {
      "send_by": null,
      "must_arrive_by": null,
      "post_too_late": false,
      "form": "written_form",
      "form_note": "In writing to the court that issued the order (§ 700, § 340 ZPO; not by e-mail), or for the record at its Rechtsantragstelle. Another Amtsgericht can take it down too, but it only counts once their record reaches the issuing court (§ 129a Abs. 3 S. 2 ZPO) — go early. The period can't be extended.",
      "channels": [
        {
          "channel": "registered_letter",
          "label": "Signed letter by Einwurf-Einschreiben",
          "allowed": true,
          "recommended": true,
          "note": "Send it to the court that issued the order. Einwurf-Einschreiben (registered letter): keep the posting receipt and ask for the delivery record (Auslieferungsbeleg) — online tracking alone is no proof (BAG 2 AZR 68/24).",
          "citation": null
        },
        {
          "channel": "in_person",
          "label": "Rechtsantragstelle (for the record)",
          "allowed": true,
          "recommended": false,
          "note": "Free: they write it down for you (zu Protokoll); bring the order and its envelope. At the court that issued the order it counts at once. Any other Amtsgericht can take it down too, but then it only counts once their record reaches the issuing court — go by the send-by date, as for a letter.",
          "citation": "§ 129a Abs. 1, 3 ZPO"
        },
        {
          "channel": "fax",
          "label": "Fax of the signed letter",
          "allowed": true,
          "recommended": false,
          "note": "Counts as written; keep the transmission report.",
          "citation": null
        },
        {
          "channel": "letter",
          "label": "Signed letter by normal post",
          "allowed": true,
          "recommended": false,
          "note": "Works, but you can't prove it arrived.",
          "citation": null
        },
        {
          "channel": "email",
          "label": "E-mail",
          "allowed": false,
          "recommended": false,
          "note": "Not valid at a court.",
          "citation": null
        }
      ],
      "tips": [
        "An objection doesn't stop enforcement by itself — ask for advice about suspending it.",
        "Keep a copy of what you send and any proof of delivery."
      ]
    },
    "notes": [
      "In writing to the court that issued the order (§ 700, § 340 ZPO; not by e-mail), or for the record at its Rechtsantragstelle. Another Amtsgericht can take it down too, but it only counts once their record reaches the issuing court (§ 129a Abs. 3 S. 2 ZPO) — go early. The period can't be extended."
    ]
  },
  "landlord_notice": {
    "guidance": {
      "send_by": null,
      "must_arrive_by": null,
      "post_too_late": false,
      "form": "text_form",
      "form_note": "Text form is enough since 2025 (§ 574b Abs. 1 BGB), but a signed letter by Einwurf-Einschreiben is the safest proof that it arrived in time.",
      "channels": [
        {
          "channel": "registered_letter",
          "label": "Signed letter by Einwurf-Einschreiben",
          "allowed": true,
          "recommended": true,
          "note": "Einwurf-Einschreiben (registered letter): keep the posting receipt and ask for the delivery record (Auslieferungsbeleg) — online tracking alone is no proof (BAG 2 AZR 68/24).",
          "citation": "§ 574b Abs. 1, 2 BGB; § 574 BGB"
        },
        {
          "channel": "in_person",
          "label": "Hand it over in person",
          "allowed": true,
          "recommended": false,
          "note": "Take a witness who has read the letter.",
          "citation": "§ 574b Abs. 1, 2 BGB; § 574 BGB"
        },
        {
          "channel": "email",
          "label": "E-mail",
          "allowed": true,
          "recommended": false,
          "note": "Valid (text form); ask the landlord to confirm receipt.",
          "citation": "§ 574b Abs. 1, 2 BGB; § 574 BGB"
        },
        {
          "channel": "letter",
          "label": "Letter by normal post",
          "allowed": true,
          "recommended": false,
          "note": "Works, but you can't prove it arrived.",
          "citation": "§ 574b Abs. 1, 2 BGB; § 574 BGB"
        }
      ],
      "tips": [
        "Get advice from a tenants' association before you send it.",
        "Keep a copy of what you send and any proof of delivery."
      ]
    },
    "notes": [
      "The objection only helps if moving out would be a hardship for you or your household. Talk to a tenants' association before you send it; the reasons follow on request."
    ]
  }
};

/** How to send a withdrawal (`send.py` `_withdrawal`; the send-by date is added per letter). */
export const WITHDRAWAL_GUIDANCE: SendGuidance = {
  "send_by": null,
  "must_arrive_by": null,
  "post_too_late": false,
  "form": "text_form",
  "form_note": "Any clear statement is enough — no reasons, no signature. Sending it in time is enough (§ 355 Abs. 1 BGB); sending the goods back alone is not a withdrawal.",
  "channels": [
    {
      "channel": "email",
      "label": "E-mail",
      "allowed": true,
      "recommended": true,
      "note": "Valid; keep the sent e-mail as proof of when you sent it.",
      "citation": "§ 355 Abs. 1, 2 BGB; § 356 Abs. 2 BGB; § 193 BGB"
    },
    {
      "channel": "online_button",
      "label": "The withdrawal button (contracts made online)",
      "allowed": true,
      "recommended": false,
      "note": "For a contract made on a website or in an app, the company must offer one since 19 June 2026; it counts when you press it — save the confirmation. Not for contracts made at the door or by phone.",
      "citation": "§ 356a BGB"
    },
    {
      "channel": "registered_letter",
      "label": "Letter by Einwurf-Einschreiben",
      "allowed": true,
      "recommended": false,
      "note": "Einwurf-Einschreiben (registered letter): keep the posting receipt and ask for the delivery record (Auslieferungsbeleg) — online tracking alone is no proof (BAG 2 AZR 68/24).",
      "citation": "§ 355 Abs. 1, 2 BGB; § 356 Abs. 2 BGB; § 193 BGB"
    },
    {
      "channel": "fax",
      "label": "Fax",
      "allowed": true,
      "recommended": false,
      "note": "Keep the transmission report.",
      "citation": "§ 355 Abs. 1, 2 BGB; § 356 Abs. 2 BGB; § 193 BGB"
    },
    {
      "channel": "letter",
      "label": "Letter by normal post",
      "allowed": true,
      "recommended": false,
      "note": "Valid, but you can't prove when you sent it.",
      "citation": "§ 355 Abs. 1, 2 BGB; § 356 Abs. 2 BGB; § 193 BGB"
    }
  ],
  "tips": [
    "Send the goods back separately, as the shop's instructions say.",
    "Keep a copy of what you send and any proof of delivery."
  ]
};

/** Weekday public holidays in Sam's Land (NW), 2025–2028: a withdrawal's last day moves off them. */
export const HOLIDAYS: string[] = ["2025-01-01", "2025-04-18", "2025-04-21", "2025-05-01", "2025-05-29", "2025-06-09", "2025-06-19", "2025-10-03", "2025-12-25", "2025-12-26", "2026-01-01", "2026-04-03", "2026-04-06", "2026-05-01", "2026-05-14", "2026-05-25", "2026-06-04", "2026-12-25", "2027-01-01", "2027-03-26", "2027-03-29", "2027-05-06", "2027-05-17", "2027-05-27", "2027-11-01", "2028-04-14", "2028-04-17", "2028-05-01", "2028-05-25", "2028-06-05", "2028-06-15", "2028-10-03", "2028-11-01", "2028-12-25", "2028-12-26"];
