// Generated by scripts/gen_mock_numbers.py from Ordnung's own code over the mock letters — do not
// edit by hand (web/scripts/mock-world.mjs gives it the letters of src/mocks/db.ts).
import type { MyNumbers, WeekEntry, WeeklySession } from "@/api/types";

/** `GET /api/numbers` for the mock demo's letters, as the real app computes it. */
export const MOCK_NUMBERS: MyNumbers = {
  "today": "2026-09-28",
  "about_you": [
    {
      "key": "num_12f8ac79887c",
      "kind": "tax_id",
      "group": "about_you",
      "name": "Tax ID (Steuer-ID)",
      "label": "Steuer-ID",
      "value": "57 216 480 354",
      "display": "57 216 480 354",
      "copy_value": "57216480354",
      "check": "ok",
      "check_note": "Passes the Steuer-ID check (§ 139b AO, the BZSt's specification). A misread digit would almost always fail it; it doesn't prove the number is yours.",
      "party_id": "pty_mustertech",
      "party_name": "Muster Tech GmbH",
      "letter": {
        "id": "doc_payslip",
        "title": "Payslip August 2026",
        "date": "2026-08-31",
        "kind": "payslip"
      },
      "letters": 1
    },
    {
      "key": "num_813ed8073e66",
      "kind": "social_insurance",
      "group": "about_you",
      "name": "Social insurance number (Rentenversicherungsnummer)",
      "label": "SV-Nummer",
      "value": "65 140300 R 005",
      "display": "65 140300 R 005",
      "copy_value": "65140300R005",
      "check": "ok",
      "check_note": "Passes the Rentenversicherungsnummer check (§ 147 SGB VI, § 2 VKVV). A misread digit would almost always fail it; it doesn't prove the number is yours.",
      "party_id": "pty_mustertech",
      "party_name": "Muster Tech GmbH",
      "letter": {
        "id": "doc_payslip",
        "title": "Payslip August 2026",
        "date": "2026-08-31",
        "kind": "payslip"
      },
      "letters": 1
    },
    {
      "key": "num_30193cef07d3",
      "kind": "health_insurance",
      "group": "about_you",
      "name": "Health insurance number (Krankenversichertennummer)",
      "label": "Versichertennummer",
      "value": "R482019379",
      "display": "R482019379",
      "copy_value": "R482019379",
      "check": "ok",
      "check_note": "Passes the Krankenversichertennummer check (§ 290 SGB V, the GKV-Spitzenverband's guideline). A misread digit would almost always fail it; it doesn't prove the number is yours.",
      "party_id": "pty_bkk",
      "party_name": "Muster BKK",
      "letter": {
        "id": "doc_bkk",
        "title": "Health insurance contributions from 1 Oct",
        "date": "2026-09-10",
        "kind": "health_insurance"
      },
      "letters": 1
    },
    {
      "key": "num_b430fd07dbff",
      "kind": "student",
      "group": "about_you",
      "name": "Student number (Matrikelnummer)",
      "label": "Matrikelnummer",
      "value": "2231847",
      "display": "2231847",
      "copy_value": "2231847",
      "check": "none",
      "check_note": null,
      "party_id": "pty_hochschule",
      "party_name": "Hochschule Musterstadt",
      "letter": {
        "id": "doc_uni",
        "title": "Re-registration for summer semester 2027",
        "date": "2026-09-22",
        "kind": "university"
      },
      "letters": 1
    },
    {
      "key": "num_adccc6d10ec9",
      "kind": "broadcasting_fee",
      "group": "about_you",
      "name": "Broadcasting fee number (Beitragsnummer)",
      "label": "Beitragsnummer",
      "value": "457 812 309",
      "display": "457 812 309",
      "copy_value": "457812309",
      "check": "none",
      "check_note": null,
      "party_id": "pty_beitrag",
      "party_name": "Beitragsservice Musterstadt",
      "letter": {
        "id": "doc_rundfunk",
        "title": "Broadcasting fee due 15 Nov",
        "date": "2026-09-01",
        "kind": "broadcasting_fee"
      },
      "letters": 1
    }
  ],
  "documents": [
    {
      "key": "num_2d309c9cd26d",
      "kind": "residence_permit",
      "name": "Residence permit",
      "number": null,
      "valid_until": "2026-11-30",
      "status": "renew_soon",
      "note": "Apply before it expires: your permit then counts as still valid until the office decides (§ 81 Abs. 4 S. 1–2 AufenthG; not for a Schengen visa) — ask for a Fiktionsbescheinigung.",
      "item_id": "itm_permit_expiry",
      "needs_check": false,
      "letter": {
        "id": "doc_abh",
        "title": "Residence permit extension — appointment 14 Oct",
        "date": "2026-09-21",
        "kind": "residence_permit"
      }
    },
    {
      "key": "num_014671123ac1",
      "kind": "passport",
      "name": "Passport",
      "number": {
        "key": "num_e0f2bcb96f76",
        "kind": "passport",
        "group": "document",
        "name": "Passport number",
        "label": "Passport no.",
        "value": "X1234567",
        "display": "X1234567",
        "copy_value": "X1234567",
        "check": "none",
        "check_note": null,
        "party_id": null,
        "party_name": null,
        "letter": {
          "id": "doc_passport",
          "title": "Passport (photo)",
          "date": "2017-02-11",
          "kind": "identity_document"
        },
        "letters": 1
      },
      "valid_until": "2027-02-10",
      "status": "renew_soon",
      "note": "Renewing a passport can take months, and a residence permit usually runs only as long as the passport.",
      "item_id": "itm_passport_expiry",
      "needs_check": true,
      "letter": {
        "id": "doc_passport",
        "title": "Passport (photo)",
        "date": "2017-02-11",
        "kind": "identity_document"
      }
    }
  ],
  "organisations": [
    {
      "party_id": "pty_abh",
      "name": "Ausländerbehörde Musterstadt",
      "kind": "immigration_office",
      "phone": "+49 1234 88-2140",
      "email": "auslaenderbehoerde@musterstadt.example",
      "website": "musterstadt.example/auslaenderbehoerde",
      "numbers": [],
      "their_numbers": [],
      "open_cases": [
        {
          "key": "num_173de0b55c3d",
          "case_id": "cas_permit",
          "title": "Residence permit extension",
          "party_id": "pty_abh",
          "party_name": "Ausländerbehörde Musterstadt",
          "references": [
            {
              "key": "num_9980e9da824e",
              "kind": "case_file",
              "group": "case",
              "name": "Case reference (Aktenzeichen)",
              "label": "Aktenzeichen",
              "value": "ABH-2026-18841",
              "display": "ABH-2026-18841",
              "copy_value": "ABH-2026-18841",
              "check": "none",
              "check_note": null,
              "party_id": "pty_abh",
              "party_name": "Ausländerbehörde Musterstadt",
              "letter": {
                "id": "doc_abh",
                "title": "Residence permit extension — appointment 14 Oct",
                "date": "2026-09-21",
                "kind": "residence_permit"
              },
              "letters": 1
            }
          ],
          "next_item": {
            "id": "itm_abh_docs",
            "title": "Prepare documents for the Ausländerbehörde",
            "kind": "task",
            "due_date": "2026-10-13",
            "send_by": null,
            "at_appointment": false,
            "needs_check": false
          },
          "open_items": 3,
          "letter": {
            "id": "doc_abh",
            "title": "Residence permit extension — appointment 14 Oct",
            "date": "2026-09-21",
            "kind": "residence_permit"
          }
        }
      ],
      "last_letter": {
        "id": "doc_abh",
        "title": "Residence permit extension — appointment 14 Oct",
        "date": "2026-09-21",
        "kind": "residence_permit"
      },
      "open_items": 4
    },
    {
      "party_id": "pty_beitrag",
      "name": "Beitragsservice Musterstadt",
      "kind": "public_broadcaster",
      "phone": null,
      "email": null,
      "website": null,
      "numbers": [
        {
          "key": "num_adccc6d10ec9",
          "kind": "broadcasting_fee",
          "group": "about_you",
          "name": "Broadcasting fee number (Beitragsnummer)",
          "label": "Beitragsnummer",
          "value": "457 812 309",
          "display": "457 812 309",
          "copy_value": "457812309",
          "check": "none",
          "check_note": null,
          "party_id": "pty_beitrag",
          "party_name": "Beitragsservice Musterstadt",
          "letter": {
            "id": "doc_rundfunk",
            "title": "Broadcasting fee due 15 Nov",
            "date": "2026-09-01",
            "kind": "broadcasting_fee"
          },
          "letters": 1
        }
      ],
      "their_numbers": [
        {
          "key": "num_41781eb5f62c",
          "kind": "iban",
          "group": "theirs",
          "name": "Bank account (IBAN)",
          "label": "IBAN for payments to Beitragsservice Musterstadt",
          "value": "DE57123489000055081836",
          "display": "DE57 1234 8900 0055 0818 36",
          "copy_value": "DE57123489000055081836",
          "check": "ok",
          "check_note": "The IBAN's check digits are valid — that only rules out typos, not fraud.",
          "party_id": "pty_beitrag",
          "party_name": "Beitragsservice Musterstadt",
          "letter": {
            "id": "doc_rundfunk",
            "title": "Broadcasting fee due 15 Nov",
            "date": "2026-09-01",
            "kind": "broadcasting_fee"
          },
          "letters": 1
        }
      ],
      "open_cases": [],
      "last_letter": {
        "id": "doc_rundfunk",
        "title": "Broadcasting fee due 15 Nov",
        "date": "2026-09-01",
        "kind": "broadcasting_fee"
      },
      "open_items": 1
    },
    {
      "party_id": "pty_fitwell",
      "name": "FitWell Studios",
      "kind": "gym",
      "phone": null,
      "email": "service@fitwell.example",
      "website": null,
      "numbers": [
        {
          "key": "num_77aa73a24ae4",
          "kind": "member",
          "group": "organisation",
          "name": "Member number",
          "label": "Mitgliedsnummer",
          "value": "FW-20931",
          "display": "FW-20931",
          "copy_value": "FW-20931",
          "check": "none",
          "check_note": null,
          "party_id": "pty_fitwell",
          "party_name": "FitWell Studios",
          "letter": {
            "id": "doc_gym_price",
            "title": "Gym price increase — FitWell",
            "date": "2026-09-14",
            "kind": "price_increase"
          },
          "letters": 2
        }
      ],
      "their_numbers": [],
      "open_cases": [],
      "last_letter": {
        "id": "doc_gym_price",
        "title": "Gym price increase — FitWell",
        "date": "2026-09-14",
        "kind": "price_increase"
      },
      "open_items": 2
    },
    {
      "party_id": "pty_funknetz",
      "name": "FunkNetz Mobil GmbH",
      "kind": "telecom",
      "phone": null,
      "email": "kuendigung@funknetz.example",
      "website": "funknetz.example",
      "numbers": [
        {
          "key": "num_b7244c9aabf6",
          "kind": "customer",
          "group": "organisation",
          "name": "Customer number",
          "label": "Kundennummer",
          "value": "7700 4412 09",
          "display": "7700 4412 09",
          "copy_value": "7700441209",
          "check": "none",
          "check_note": null,
          "party_id": "pty_funknetz",
          "party_name": "FunkNetz Mobil GmbH",
          "letter": {
            "id": "doc_phone",
            "title": "Phone contract — FunkNetz Allnet L",
            "date": "2024-10-15",
            "kind": "contract"
          },
          "letters": 1
        }
      ],
      "their_numbers": [],
      "open_cases": [],
      "last_letter": {
        "id": "doc_phone",
        "title": "Phone contract — FunkNetz Allnet L",
        "date": "2024-10-15",
        "kind": "contract"
      },
      "open_items": 1
    },
    {
      "party_id": "pty_hochschule",
      "name": "Hochschule Musterstadt",
      "kind": "university",
      "phone": null,
      "email": "studierendenservice@hs-musterstadt.example",
      "website": null,
      "numbers": [
        {
          "key": "num_b430fd07dbff",
          "kind": "student",
          "group": "about_you",
          "name": "Student number (Matrikelnummer)",
          "label": "Matrikelnummer",
          "value": "2231847",
          "display": "2231847",
          "copy_value": "2231847",
          "check": "none",
          "check_note": null,
          "party_id": "pty_hochschule",
          "party_name": "Hochschule Musterstadt",
          "letter": {
            "id": "doc_uni",
            "title": "Re-registration for summer semester 2027",
            "date": "2026-09-22",
            "kind": "university"
          },
          "letters": 1
        }
      ],
      "their_numbers": [
        {
          "key": "num_5c223559b27e",
          "kind": "iban",
          "group": "theirs",
          "name": "Bank account (IBAN)",
          "label": "IBAN for payments to Hochschule Musterstadt",
          "value": "DE10123456000007700220",
          "display": "DE10 1234 5600 0007 7002 20",
          "copy_value": "DE10123456000007700220",
          "check": "ok",
          "check_note": "The IBAN's check digits are valid — that only rules out typos, not fraud.",
          "party_id": "pty_hochschule",
          "party_name": "Hochschule Musterstadt",
          "letter": {
            "id": "doc_uni",
            "title": "Re-registration for summer semester 2027",
            "date": "2026-09-22",
            "kind": "university"
          },
          "letters": 1
        }
      ],
      "open_cases": [],
      "last_letter": {
        "id": "doc_uni",
        "title": "Re-registration for summer semester 2027",
        "date": "2026-09-22",
        "kind": "university"
      },
      "open_items": 1
    },
    {
      "party_id": "pty_bkk",
      "name": "Muster BKK",
      "kind": "health_insurer",
      "phone": null,
      "email": "post@muster-bkk.example",
      "website": null,
      "numbers": [
        {
          "key": "num_30193cef07d3",
          "kind": "health_insurance",
          "group": "about_you",
          "name": "Health insurance number (Krankenversichertennummer)",
          "label": "Versichertennummer",
          "value": "R482019379",
          "display": "R482019379",
          "copy_value": "R482019379",
          "check": "ok",
          "check_note": "Passes the Krankenversichertennummer check (§ 290 SGB V, the GKV-Spitzenverband's guideline). A misread digit would almost always fail it; it doesn't prove the number is yours.",
          "party_id": "pty_bkk",
          "party_name": "Muster BKK",
          "letter": {
            "id": "doc_bkk",
            "title": "Health insurance contributions from 1 Oct",
            "date": "2026-09-10",
            "kind": "health_insurance"
          },
          "letters": 1
        }
      ],
      "their_numbers": [],
      "open_cases": [],
      "last_letter": {
        "id": "doc_bkk",
        "title": "Health insurance contributions from 1 Oct",
        "date": "2026-09-10",
        "kind": "health_insurance"
      },
      "open_items": 1
    },
    {
      "party_id": "pty_mustertech",
      "name": "Muster Tech GmbH",
      "kind": "employer",
      "phone": null,
      "email": "people@mustertech.example",
      "website": null,
      "numbers": [
        {
          "key": "num_12f8ac79887c",
          "kind": "tax_id",
          "group": "about_you",
          "name": "Tax ID (Steuer-ID)",
          "label": "Steuer-ID",
          "value": "57 216 480 354",
          "display": "57 216 480 354",
          "copy_value": "57216480354",
          "check": "ok",
          "check_note": "Passes the Steuer-ID check (§ 139b AO, the BZSt's specification). A misread digit would almost always fail it; it doesn't prove the number is yours.",
          "party_id": "pty_mustertech",
          "party_name": "Muster Tech GmbH",
          "letter": {
            "id": "doc_payslip",
            "title": "Payslip August 2026",
            "date": "2026-08-31",
            "kind": "payslip"
          },
          "letters": 1
        },
        {
          "key": "num_813ed8073e66",
          "kind": "social_insurance",
          "group": "about_you",
          "name": "Social insurance number (Rentenversicherungsnummer)",
          "label": "SV-Nummer",
          "value": "65 140300 R 005",
          "display": "65 140300 R 005",
          "copy_value": "65140300R005",
          "check": "ok",
          "check_note": "Passes the Rentenversicherungsnummer check (§ 147 SGB VI, § 2 VKVV). A misread digit would almost always fail it; it doesn't prove the number is yours.",
          "party_id": "pty_mustertech",
          "party_name": "Muster Tech GmbH",
          "letter": {
            "id": "doc_payslip",
            "title": "Payslip August 2026",
            "date": "2026-08-31",
            "kind": "payslip"
          },
          "letters": 1
        },
        {
          "key": "num_e588146b7dcf",
          "kind": "employee",
          "group": "organisation",
          "name": "Employee number",
          "label": "Personalnummer",
          "value": "WS-0417",
          "display": "WS-0417",
          "copy_value": "WS-0417",
          "check": "none",
          "check_note": null,
          "party_id": "pty_mustertech",
          "party_name": "Muster Tech GmbH",
          "letter": {
            "id": "doc_payslip",
            "title": "Payslip August 2026",
            "date": "2026-08-31",
            "kind": "payslip"
          },
          "letters": 2
        }
      ],
      "their_numbers": [],
      "open_cases": [],
      "last_letter": {
        "id": "doc_payslip",
        "title": "Payslip August 2026",
        "date": "2026-08-31",
        "kind": "payslip"
      },
      "open_items": 1
    },
    {
      "party_id": "pty_versicherung",
      "name": "Muster Versicherung AG",
      "kind": "insurer",
      "phone": null,
      "email": "service@muster-versicherung.example",
      "website": null,
      "numbers": [
        {
          "key": "num_ecc321f95fe7",
          "kind": "policy",
          "group": "organisation",
          "name": "Policy number",
          "label": "Versicherungsnummer",
          "value": "PHV-4471-2290",
          "display": "PHV-4471-2290",
          "copy_value": "PHV-4471-2290",
          "check": "none",
          "check_note": null,
          "party_id": "pty_versicherung",
          "party_name": "Muster Versicherung AG",
          "letter": {
            "id": "doc_liability",
            "title": "Liability insurance policy",
            "date": "2024-11-20",
            "kind": "insurance"
          },
          "letters": 1
        }
      ],
      "their_numbers": [],
      "open_cases": [],
      "last_letter": {
        "id": "doc_liability",
        "title": "Liability insurance policy",
        "date": "2024-11-20",
        "kind": "insurance"
      },
      "open_items": 1
    },
    {
      "party_id": "pty_ordnungsamt",
      "name": "Ordnungsamt Musterstadt",
      "kind": "authority",
      "phone": null,
      "email": null,
      "website": null,
      "numbers": [],
      "their_numbers": [
        {
          "key": "num_bc79a5527382",
          "kind": "iban",
          "group": "theirs",
          "name": "Bank account (IBAN)",
          "label": "IBAN for payments to Stadtkasse Musterstadt",
          "value": "DE51123456000000100017",
          "display": "DE51 1234 5600 0000 1000 17",
          "copy_value": "DE51123456000000100017",
          "check": "ok",
          "check_note": "The IBAN's check digits are valid — that only rules out typos, not fraud.",
          "party_id": "pty_ordnungsamt",
          "party_name": "Ordnungsamt Musterstadt",
          "letter": {
            "id": "doc_parking",
            "title": "Parking fine (Verwarnungsgeld)",
            "date": "2026-09-22",
            "kind": "fine"
          },
          "letters": 1
        }
      ],
      "open_cases": [
        {
          "key": "num_fc11dc6530b5",
          "case_id": "cas_parking",
          "title": "Parking fine OA-VW-2026-55012",
          "party_id": "pty_ordnungsamt",
          "party_name": "Ordnungsamt Musterstadt",
          "references": [
            {
              "key": "num_c612b78413ea",
              "kind": "case_file",
              "group": "case",
              "name": "Case reference (Aktenzeichen)",
              "label": "Aktenzeichen",
              "value": "OA-VW-2026-55012",
              "display": "OA-VW-2026-55012",
              "copy_value": "OA-VW-2026-55012",
              "check": "none",
              "check_note": null,
              "party_id": "pty_ordnungsamt",
              "party_name": "Ordnungsamt Musterstadt",
              "letter": {
                "id": "doc_parking",
                "title": "Parking fine (Verwarnungsgeld)",
                "date": "2026-09-22",
                "kind": "fine"
              },
              "letters": 1
            }
          ],
          "next_item": {
            "id": "itm_parking",
            "title": "Pay the parking fine",
            "kind": "payment",
            "due_date": "2026-09-29",
            "send_by": null,
            "at_appointment": false,
            "needs_check": true
          },
          "open_items": 1,
          "letter": {
            "id": "doc_parking",
            "title": "Parking fine (Verwarnungsgeld)",
            "date": "2026-09-22",
            "kind": "fine"
          }
        }
      ],
      "last_letter": {
        "id": "doc_parking",
        "title": "Parking fine (Verwarnungsgeld)",
        "date": "2026-09-22",
        "kind": "fine"
      },
      "open_items": 1
    },
    {
      "party_id": "pty_stadtwerke",
      "name": "Stadtwerke Musterstadt",
      "kind": "utility",
      "phone": "+49 1234 700-0",
      "email": "kundenservice@stadtwerke-musterstadt.example",
      "website": "stadtwerke-musterstadt.example",
      "numbers": [
        {
          "key": "num_957170e1d7f0",
          "kind": "customer",
          "group": "organisation",
          "name": "Customer number",
          "label": "Kundennummer",
          "value": "300 512 877",
          "display": "300 512 877",
          "copy_value": "300512877",
          "check": "none",
          "check_note": null,
          "party_id": "pty_stadtwerke",
          "party_name": "Stadtwerke Musterstadt",
          "letter": {
            "id": "doc_power",
            "title": "Electricity contract — MusterStrom Natur",
            "date": "2025-09-20",
            "kind": "contract"
          },
          "letters": 1
        }
      ],
      "their_numbers": [],
      "open_cases": [],
      "last_letter": {
        "id": "doc_power",
        "title": "Electricity contract — MusterStrom Natur",
        "date": "2025-09-20",
        "kind": "contract"
      },
      "open_items": 1
    },
    {
      "party_id": "pty_techmarkt",
      "name": "TechMarkt Online GmbH",
      "kind": "retailer",
      "phone": null,
      "email": "buchhaltung@techmarkt.example",
      "website": null,
      "numbers": [],
      "their_numbers": [
        {
          "key": "num_0039286f1edb",
          "kind": "iban",
          "group": "theirs",
          "name": "Bank account (IBAN)",
          "label": "IBAN for payments to TechMarkt Online GmbH",
          "value": "DE70123478000048213000",
          "display": "DE70 1234 7800 0048 2130 00",
          "copy_value": "DE70123478000048213000",
          "check": "ok",
          "check_note": "The IBAN's check digits are valid — that only rules out typos, not fraud.",
          "party_id": "pty_techmarkt",
          "party_name": "TechMarkt Online GmbH",
          "letter": {
            "id": "doc_tm_dunning",
            "title": "TechMarkt payment reminder",
            "date": "2026-09-18",
            "kind": "dunning"
          },
          "letters": 2
        }
      ],
      "open_cases": [
        {
          "key": "num_498b6da359a9",
          "case_id": "cas_techmarkt",
          "title": "TechMarkt order 4711-2026",
          "party_id": "pty_techmarkt",
          "party_name": "TechMarkt Online GmbH",
          "references": [
            {
              "key": "num_68b830ed1cb2",
              "kind": "invoice",
              "group": "case",
              "name": "Invoice number",
              "label": "Rechnungsnummer",
              "value": "RE-2026-084213",
              "display": "RE-2026-084213",
              "copy_value": "RE-2026-084213",
              "check": "none",
              "check_note": null,
              "party_id": "pty_techmarkt",
              "party_name": "TechMarkt Online GmbH",
              "letter": {
                "id": "doc_tm_dunning",
                "title": "TechMarkt payment reminder",
                "date": "2026-09-18",
                "kind": "dunning"
              },
              "letters": 2
            }
          ],
          "next_item": {
            "id": "itm_tm_dunning",
            "title": "Pay TechMarkt reminder",
            "kind": "payment",
            "due_date": "2026-09-30",
            "send_by": null,
            "at_appointment": false,
            "needs_check": false
          },
          "open_items": 1,
          "letter": {
            "id": "doc_tm_dunning",
            "title": "TechMarkt payment reminder",
            "date": "2026-09-18",
            "kind": "dunning"
          }
        }
      ],
      "last_letter": {
        "id": "doc_tm_dunning",
        "title": "TechMarkt payment reminder",
        "date": "2026-09-18",
        "kind": "dunning"
      },
      "open_items": 1
    },
    {
      "party_id": "pty_wohnbau",
      "name": "Wohnbau Musterstadt eG",
      "kind": "landlord",
      "phone": "+49 1234 5566-0",
      "email": "vermietung@wohnbau-musterstadt.example",
      "website": "wohnbau-musterstadt.example",
      "numbers": [
        {
          "key": "num_d0e9fbf1343e",
          "kind": "customer",
          "group": "organisation",
          "name": "Customer number",
          "label": "Mieternummer",
          "value": "12-0412-07",
          "display": "12-0412-07",
          "copy_value": "12-0412-07",
          "check": "none",
          "check_note": null,
          "party_id": "pty_wohnbau",
          "party_name": "Wohnbau Musterstadt eG",
          "letter": {
            "id": "doc_nebenkosten",
            "title": "Utility cost statement 2025",
            "date": "2026-09-09",
            "kind": "utility_bill"
          },
          "letters": 2
        }
      ],
      "their_numbers": [
        {
          "key": "num_5620bcfc42c6",
          "kind": "iban",
          "group": "theirs",
          "name": "Bank account (IBAN)",
          "label": "IBAN for payments to Wohnbau Musterstadt eG",
          "value": "DE05123456000004455660",
          "display": "DE05 1234 5600 0004 4556 60",
          "copy_value": "DE05123456000004455660",
          "check": "ok",
          "check_note": "The IBAN's check digits are valid — that only rules out typos, not fraud.",
          "party_id": "pty_wohnbau",
          "party_name": "Wohnbau Musterstadt eG",
          "letter": {
            "id": "doc_nebenkosten",
            "title": "Utility cost statement 2025",
            "date": "2026-09-09",
            "kind": "utility_bill"
          },
          "letters": 2
        }
      ],
      "open_cases": [],
      "last_letter": {
        "id": "doc_nebenkosten",
        "title": "Utility cost statement 2025",
        "date": "2026-09-09",
        "kind": "utility_bill"
      },
      "open_items": 3
    }
  ],
  "open_cases": [
    {
      "key": "num_fc11dc6530b5",
      "case_id": "cas_parking",
      "title": "Parking fine OA-VW-2026-55012",
      "party_id": "pty_ordnungsamt",
      "party_name": "Ordnungsamt Musterstadt",
      "references": [
        {
          "key": "num_c612b78413ea",
          "kind": "case_file",
          "group": "case",
          "name": "Case reference (Aktenzeichen)",
          "label": "Aktenzeichen",
          "value": "OA-VW-2026-55012",
          "display": "OA-VW-2026-55012",
          "copy_value": "OA-VW-2026-55012",
          "check": "none",
          "check_note": null,
          "party_id": "pty_ordnungsamt",
          "party_name": "Ordnungsamt Musterstadt",
          "letter": {
            "id": "doc_parking",
            "title": "Parking fine (Verwarnungsgeld)",
            "date": "2026-09-22",
            "kind": "fine"
          },
          "letters": 1
        }
      ],
      "next_item": {
        "id": "itm_parking",
        "title": "Pay the parking fine",
        "kind": "payment",
        "due_date": "2026-09-29",
        "send_by": null,
        "at_appointment": false,
        "needs_check": true
      },
      "open_items": 1,
      "letter": {
        "id": "doc_parking",
        "title": "Parking fine (Verwarnungsgeld)",
        "date": "2026-09-22",
        "kind": "fine"
      }
    },
    {
      "key": "num_498b6da359a9",
      "case_id": "cas_techmarkt",
      "title": "TechMarkt order 4711-2026",
      "party_id": "pty_techmarkt",
      "party_name": "TechMarkt Online GmbH",
      "references": [
        {
          "key": "num_68b830ed1cb2",
          "kind": "invoice",
          "group": "case",
          "name": "Invoice number",
          "label": "Rechnungsnummer",
          "value": "RE-2026-084213",
          "display": "RE-2026-084213",
          "copy_value": "RE-2026-084213",
          "check": "none",
          "check_note": null,
          "party_id": "pty_techmarkt",
          "party_name": "TechMarkt Online GmbH",
          "letter": {
            "id": "doc_tm_dunning",
            "title": "TechMarkt payment reminder",
            "date": "2026-09-18",
            "kind": "dunning"
          },
          "letters": 2
        }
      ],
      "next_item": {
        "id": "itm_tm_dunning",
        "title": "Pay TechMarkt reminder",
        "kind": "payment",
        "due_date": "2026-09-30",
        "send_by": null,
        "at_appointment": false,
        "needs_check": false
      },
      "open_items": 1,
      "letter": {
        "id": "doc_tm_dunning",
        "title": "TechMarkt payment reminder",
        "date": "2026-09-18",
        "kind": "dunning"
      }
    },
    {
      "key": "num_173de0b55c3d",
      "case_id": "cas_permit",
      "title": "Residence permit extension",
      "party_id": "pty_abh",
      "party_name": "Ausländerbehörde Musterstadt",
      "references": [
        {
          "key": "num_9980e9da824e",
          "kind": "case_file",
          "group": "case",
          "name": "Case reference (Aktenzeichen)",
          "label": "Aktenzeichen",
          "value": "ABH-2026-18841",
          "display": "ABH-2026-18841",
          "copy_value": "ABH-2026-18841",
          "check": "none",
          "check_note": null,
          "party_id": "pty_abh",
          "party_name": "Ausländerbehörde Musterstadt",
          "letter": {
            "id": "doc_abh",
            "title": "Residence permit extension — appointment 14 Oct",
            "date": "2026-09-21",
            "kind": "residence_permit"
          },
          "letters": 1
        }
      ],
      "next_item": {
        "id": "itm_abh_docs",
        "title": "Prepare documents for the Ausländerbehörde",
        "kind": "task",
        "due_date": "2026-10-13",
        "send_by": null,
        "at_appointment": false,
        "needs_check": false
      },
      "open_items": 3,
      "letter": {
        "id": "doc_abh",
        "title": "Residence permit extension — appointment 14 Oct",
        "date": "2026-09-21",
        "kind": "residence_permit"
      }
    }
  ]
};

/** `GET /api/week` for the mock demo's letters on its today, before any session. */
export const MOCK_WEEK: WeeklySession = {
  "today": "2026-09-28",
  "since": "2026-09-21",
  "last_session": null,
  "due": true,
  "next_prompt": null,
  "minutes": 10,
  "steps": [
    {
      "id": "new",
      "title": "New in the last 7 days",
      "summary": "8 letters since Mon 21 Sep",
      "entries": [
        {
          "key": "document:doc_folder_scan",
          "ref": {
            "type": "document",
            "id": "doc_folder_scan"
          },
          "title": "Scan_2026-09-28_0914.pdf",
          "kind": "other",
          "date": "2026-09-28",
          "date_role": "added",
          "due_date": null,
          "amount": null,
          "currency": null,
          "party_id": null,
          "party_name": null,
          "doc_id": "doc_folder_scan",
          "status": "held",
          "note": "Waiting for you — read it with Claude or keep it private.",
          "tone": "warn",
          "overdue": false,
          "item": null
        },
        {
          "key": "document:doc_folder_mail",
          "ref": {
            "type": "document",
            "id": "doc_folder_mail"
          },
          "title": "Ihre Rechnung September 2026 · FunkNetz Kundenservice",
          "kind": "other",
          "date": "2026-09-27",
          "date_role": "added",
          "due_date": null,
          "amount": null,
          "currency": null,
          "party_id": null,
          "party_name": null,
          "doc_id": "doc_folder_mail",
          "status": "held",
          "note": "Waiting for you — read it with Claude or keep it private.",
          "tone": "warn",
          "overdue": false,
          "item": null
        },
        {
          "key": "document:doc_folder_invoice",
          "ref": {
            "type": "document",
            "id": "doc_folder_invoice"
          },
          "title": "Rechnung_2026-09_FunkNetz.pdf",
          "kind": "other",
          "date": "2026-09-27",
          "date_role": "added",
          "due_date": null,
          "amount": null,
          "currency": null,
          "party_id": null,
          "party_name": null,
          "doc_id": "doc_folder_invoice",
          "status": "held",
          "note": "Waiting for you — read it with Claude or keep it private.",
          "tone": "warn",
          "overdue": false,
          "item": null
        },
        {
          "key": "document:doc_library",
          "ref": {
            "type": "document",
            "id": "doc_library"
          },
          "title": "Library: overdue books",
          "kind": "dunning",
          "date": "2026-09-26",
          "date_role": "added",
          "due_date": null,
          "amount": null,
          "currency": null,
          "party_id": "pty_library",
          "party_name": "Stadtbibliothek Musterstadt",
          "doc_id": "doc_library",
          "status": "processed",
          "note": "2 open to-dos",
          "tone": "neutral",
          "overdue": false,
          "item": null
        },
        {
          "key": "document:doc_dentist",
          "ref": {
            "type": "document",
            "id": "doc_dentist"
          },
          "title": "Dentist appointment reminder",
          "kind": "appointment",
          "date": "2026-09-25",
          "date_role": "added",
          "due_date": null,
          "amount": null,
          "currency": null,
          "party_id": "pty_dentist",
          "party_name": "Zahnarztpraxis Dr. Muster",
          "doc_id": "doc_dentist",
          "status": "processed",
          "note": "1 open to-do",
          "tone": "neutral",
          "overdue": false,
          "item": null
        },
        {
          "key": "document:doc_parking",
          "ref": {
            "type": "document",
            "id": "doc_parking"
          },
          "title": "Parking fine (Verwarnungsgeld)",
          "kind": "fine",
          "date": "2026-09-24",
          "date_role": "added",
          "due_date": null,
          "amount": null,
          "currency": null,
          "party_id": "pty_ordnungsamt",
          "party_name": "Ordnungsamt Musterstadt",
          "doc_id": "doc_parking",
          "status": "needs_review",
          "note": "Please check what Ordnung read.",
          "tone": "warn",
          "overdue": false,
          "item": null
        },
        {
          "key": "document:doc_uni",
          "ref": {
            "type": "document",
            "id": "doc_uni"
          },
          "title": "Re-registration for summer semester 2027",
          "kind": "university",
          "date": "2026-09-23",
          "date_role": "added",
          "due_date": null,
          "amount": null,
          "currency": null,
          "party_id": "pty_hochschule",
          "party_name": "Hochschule Musterstadt",
          "doc_id": "doc_uni",
          "status": "processed",
          "note": "1 open to-do",
          "tone": "neutral",
          "overdue": false,
          "item": null
        },
        {
          "key": "document:doc_abh",
          "ref": {
            "type": "document",
            "id": "doc_abh"
          },
          "title": "Residence permit extension — appointment 14 Oct",
          "kind": "residence_permit",
          "date": "2026-09-22",
          "date_role": "added",
          "due_date": null,
          "amount": null,
          "currency": null,
          "party_id": "pty_abh",
          "party_name": "Ausländerbehörde Musterstadt",
          "doc_id": "doc_abh",
          "status": "processed",
          "note": "4 open to-dos",
          "tone": "neutral",
          "overdue": false,
          "item": null
        }
      ],
      "more": 0,
      "total": null,
      "total_other_currencies": {}
    },
    {
      "id": "check",
      "title": "Please check",
      "summary": "2 things to compare with the letter",
      "entries": [
        {
          "key": "item:itm_parking",
          "ref": {
            "type": "item",
            "id": "itm_parking"
          },
          "title": "Pay the parking fine",
          "kind": "payment",
          "date": "2026-09-29",
          "date_role": "pay_by",
          "due_date": null,
          "amount": 30.0,
          "currency": "EUR",
          "party_id": "pty_ordnungsamt",
          "party_name": "Ordnungsamt Musterstadt",
          "doc_id": "doc_parking",
          "status": "open",
          "note": "Read by AI from a photo — compare it with the paper letter.",
          "tone": "warn",
          "overdue": false,
          "item": {
            "id": "itm_parking",
            "kind": "payment",
            "title": "Pay the parking fine",
            "description": "Verwarnungsgeld OA-VW-2026-55012 (Bahnhofstraße 8, 17 Sep).",
            "action": "Transfer €30 to the Stadtkasse with the reference OA-VW-2026-55012.",
            "consequence": "A formal fine procedure starts, with extra fees.",
            "due_date": "2026-09-29",
            "due_time": null,
            "send_by": null,
            "date_spec": {
              "type": "relative",
              "date": null,
              "time": null,
              "anchor": "receipt",
              "anchor_date": null,
              "amount": 1,
              "unit": "weeks",
              "delivery_rule": "none",
              "shift_rule": "auto",
              "nature": "payment",
              "legal_basis": null,
              "text": "Bitte zahlen Sie das Verwarnungsgeld innerhalb einer Woche nach Zugang dieses Schreibens."
            },
            "computation": {
              "due_date": "2026-09-29",
              "send_by": null,
              "safe_date": null,
              "holiday_calendar": "Germany + North Rhine-Westphalia (NW)",
              "summary": "The week starts when the letter reached you, which we don't know yet. Counting from the letter date (Tue 22 Sep) — the earliest possible — gives Tue 29 Sep.",
              "steps": [
                {
                  "label": "Letter dated",
                  "date": "2026-09-22",
                  "rule_id": null,
                  "citation": null
                },
                {
                  "label": "Arrival date unknown — using the letter date instead (earliest possible)",
                  "date": "2026-09-22",
                  "rule_id": "receipt_fallback",
                  "citation": null
                },
                {
                  "label": "One week later",
                  "date": "2026-09-29",
                  "rule_id": "bgb_188",
                  "citation": "§ 188 Abs. 2 BGB"
                }
              ],
              "rule_ids": [
                "receipt_fallback",
                "bgb_188"
              ],
              "warnings": [
                "Tell us when the letter arrived to get the exact date."
              ],
              "confidence": "low"
            },
            "amount": 30.0,
            "currency": "EUR",
            "direction": "out",
            "recurrence": null,
            "status": "open",
            "snoozed_until": null,
            "priority": "high",
            "area": "mobility",
            "party_id": "pty_ordnungsamt",
            "case_id": "cas_parking",
            "contract_id": null,
            "doc_id": "doc_parking",
            "evidence": [
              {
                "doc_id": "doc_parking",
                "page": 1,
                "quote": "Bitte zahlen Sie das Verwarnungsgeld innerhalb einer Woche nach Zugang dieses Schreibens.",
                "grounding": "model_read",
                "value_consistent": true,
                "score": 0.97,
                "boxes": [
                  {
                    "page": 1,
                    "x0": 0.1615,
                    "y0": 0.4472,
                    "x1": 0.8263,
                    "y1": 0.4599
                  }
                ]
              }
            ],
            "grounding": "model_read",
            "slot_key": "slot_itm_parking",
            "user_modified": false,
            "due_date_source": "computed",
            "origin": "extracted",
            "location": null,
            "filed_on": null,
            "created_at": "2026-09-24T18:15:00Z",
            "updated_at": "2026-09-24T18:15:00Z",
            "completed_at": null
          }
        },
        {
          "key": "item:itm_passport_expiry",
          "ref": {
            "type": "item",
            "id": "itm_passport_expiry"
          },
          "title": "Passport expires",
          "kind": "expiry",
          "date": "2027-02-10",
          "date_role": "expires",
          "due_date": null,
          "amount": null,
          "currency": null,
          "party_id": null,
          "party_name": null,
          "doc_id": "doc_passport",
          "status": "open",
          "note": "Read by AI from a photo — compare it with the paper letter.",
          "tone": "warn",
          "overdue": false,
          "item": {
            "id": "itm_passport_expiry",
            "kind": "expiry",
            "title": "Passport expires",
            "description": null,
            "action": null,
            "consequence": null,
            "due_date": "2027-02-10",
            "due_time": null,
            "send_by": null,
            "date_spec": null,
            "computation": null,
            "amount": null,
            "currency": null,
            "direction": null,
            "recurrence": null,
            "status": "open",
            "snoozed_until": null,
            "priority": "high",
            "area": "residence",
            "party_id": null,
            "case_id": "cas_permit",
            "contract_id": null,
            "doc_id": "doc_passport",
            "evidence": [
              {
                "doc_id": "doc_passport",
                "page": 1,
                "quote": "10 FEB 2027",
                "grounding": "model_read",
                "value_consistent": true,
                "score": 0.97,
                "boxes": [
                  {
                    "page": 1,
                    "x0": 0.6616,
                    "y0": 0.3472,
                    "x1": 0.7641,
                    "y1": 0.3599
                  }
                ]
              }
            ],
            "grounding": "model_read",
            "slot_key": "slot_itm_passport_expiry",
            "user_modified": false,
            "due_date_source": "fixed",
            "origin": "extracted",
            "location": null,
            "filed_on": null,
            "created_at": "2026-01-12T19:53:00Z",
            "updated_at": "2026-01-12T19:53:00Z",
            "completed_at": null
          }
        }
      ],
      "more": 0,
      "total": null,
      "total_other_currencies": {}
    },
    {
      "id": "pay",
      "title": "Pay this week",
      "summary": "4 transfers to make · 4 more payments in the next 30 days",
      "entries": [
        {
          "key": "item:itm_parking",
          "ref": {
            "type": "item",
            "id": "itm_parking"
          },
          "title": "Pay the parking fine",
          "kind": "payment",
          "date": "2026-09-29",
          "date_role": "pay_by",
          "due_date": null,
          "amount": 30.0,
          "currency": "EUR",
          "party_id": "pty_ordnungsamt",
          "party_name": "Ordnungsamt Musterstadt",
          "doc_id": "doc_parking",
          "status": "open",
          "note": "The amount wasn't confirmed against the letter — check it before paying.",
          "tone": "warn",
          "overdue": false,
          "item": {
            "id": "itm_parking",
            "kind": "payment",
            "title": "Pay the parking fine",
            "description": "Verwarnungsgeld OA-VW-2026-55012 (Bahnhofstraße 8, 17 Sep).",
            "action": "Transfer €30 to the Stadtkasse with the reference OA-VW-2026-55012.",
            "consequence": "A formal fine procedure starts, with extra fees.",
            "due_date": "2026-09-29",
            "due_time": null,
            "send_by": null,
            "date_spec": {
              "type": "relative",
              "date": null,
              "time": null,
              "anchor": "receipt",
              "anchor_date": null,
              "amount": 1,
              "unit": "weeks",
              "delivery_rule": "none",
              "shift_rule": "auto",
              "nature": "payment",
              "legal_basis": null,
              "text": "Bitte zahlen Sie das Verwarnungsgeld innerhalb einer Woche nach Zugang dieses Schreibens."
            },
            "computation": {
              "due_date": "2026-09-29",
              "send_by": null,
              "safe_date": null,
              "holiday_calendar": "Germany + North Rhine-Westphalia (NW)",
              "summary": "The week starts when the letter reached you, which we don't know yet. Counting from the letter date (Tue 22 Sep) — the earliest possible — gives Tue 29 Sep.",
              "steps": [
                {
                  "label": "Letter dated",
                  "date": "2026-09-22",
                  "rule_id": null,
                  "citation": null
                },
                {
                  "label": "Arrival date unknown — using the letter date instead (earliest possible)",
                  "date": "2026-09-22",
                  "rule_id": "receipt_fallback",
                  "citation": null
                },
                {
                  "label": "One week later",
                  "date": "2026-09-29",
                  "rule_id": "bgb_188",
                  "citation": "§ 188 Abs. 2 BGB"
                }
              ],
              "rule_ids": [
                "receipt_fallback",
                "bgb_188"
              ],
              "warnings": [
                "Tell us when the letter arrived to get the exact date."
              ],
              "confidence": "low"
            },
            "amount": 30.0,
            "currency": "EUR",
            "direction": "out",
            "recurrence": null,
            "status": "open",
            "snoozed_until": null,
            "priority": "high",
            "area": "mobility",
            "party_id": "pty_ordnungsamt",
            "case_id": "cas_parking",
            "contract_id": null,
            "doc_id": "doc_parking",
            "evidence": [
              {
                "doc_id": "doc_parking",
                "page": 1,
                "quote": "Bitte zahlen Sie das Verwarnungsgeld innerhalb einer Woche nach Zugang dieses Schreibens.",
                "grounding": "model_read",
                "value_consistent": true,
                "score": 0.97,
                "boxes": [
                  {
                    "page": 1,
                    "x0": 0.1615,
                    "y0": 0.4472,
                    "x1": 0.8263,
                    "y1": 0.4599
                  }
                ]
              }
            ],
            "grounding": "model_read",
            "slot_key": "slot_itm_parking",
            "user_modified": false,
            "due_date_source": "computed",
            "origin": "extracted",
            "location": null,
            "filed_on": null,
            "created_at": "2026-09-24T18:15:00Z",
            "updated_at": "2026-09-24T18:15:00Z",
            "completed_at": null
          }
        },
        {
          "key": "item:itm_tm_dunning",
          "ref": {
            "type": "item",
            "id": "itm_tm_dunning"
          },
          "title": "Pay TechMarkt reminder",
          "kind": "payment",
          "date": "2026-09-30",
          "date_role": "pay_by",
          "due_date": null,
          "amount": 94.99,
          "currency": "EUR",
          "party_id": "pty_techmarkt",
          "party_name": "TechMarkt Online GmbH",
          "doc_id": "doc_tm_dunning",
          "status": "open",
          "note": null,
          "tone": "neutral",
          "overdue": false,
          "item": {
            "id": "itm_tm_dunning",
            "kind": "payment",
            "title": "Pay TechMarkt reminder",
            "description": "Invoice RE-2026-084213 (USB-C dock) plus €5 reminder fee.",
            "action": "Transfer €94.99 with the reference RE-2026-084213 — or reply with proof if you already paid.",
            "consequence": "They may pass the debt to a collection agency (more fees).",
            "due_date": "2026-09-30",
            "due_time": null,
            "send_by": null,
            "date_spec": {
              "type": "fixed",
              "date": "2026-09-30",
              "time": null,
              "anchor": null,
              "anchor_date": null,
              "amount": null,
              "unit": null,
              "delivery_rule": "none",
              "shift_rule": "auto",
              "nature": "payment",
              "legal_basis": null,
              "text": "Bitte überweisen Sie den Gesamtbetrag von 94,99 EUR bis zum 30.09.2026."
            },
            "computation": null,
            "amount": 94.99,
            "currency": "EUR",
            "direction": "out",
            "recurrence": null,
            "status": "open",
            "snoozed_until": null,
            "priority": "high",
            "area": "money",
            "party_id": "pty_techmarkt",
            "case_id": "cas_techmarkt",
            "contract_id": null,
            "doc_id": "doc_tm_dunning",
            "evidence": [
              {
                "doc_id": "doc_tm_dunning",
                "page": 1,
                "quote": "Bitte überweisen Sie den Gesamtbetrag von 94,99 EUR bis zum 30.09.2026.",
                "grounding": "verified",
                "value_consistent": true,
                "score": 0.97,
                "boxes": [
                  {
                    "page": 1,
                    "x0": 0.1185,
                    "y0": 0.5274,
                    "x1": 0.7269,
                    "y1": 0.5417
                  }
                ]
              }
            ],
            "grounding": "verified",
            "slot_key": "slot_itm_tm_dunning",
            "user_modified": false,
            "due_date_source": "fixed",
            "origin": "extracted",
            "location": null,
            "filed_on": null,
            "created_at": "2026-09-19T08:32:00Z",
            "updated_at": "2026-09-19T08:32:00Z",
            "completed_at": null
          }
        },
        {
          "key": "item:itm_library_fee",
          "ref": {
            "type": "item",
            "id": "itm_library_fee"
          },
          "title": "Pay library fee",
          "kind": "payment",
          "date": "2026-10-02",
          "date_role": "pay_by",
          "due_date": null,
          "amount": 4.5,
          "currency": "EUR",
          "party_id": "pty_library",
          "party_name": "Stadtbibliothek Musterstadt",
          "doc_id": "doc_library",
          "status": "open",
          "note": null,
          "tone": "neutral",
          "overdue": false,
          "item": {
            "id": "itm_library_fee",
            "kind": "payment",
            "title": "Pay library fee",
            "description": null,
            "action": null,
            "consequence": null,
            "due_date": "2026-10-02",
            "due_time": null,
            "send_by": null,
            "date_spec": null,
            "computation": null,
            "amount": 4.5,
            "currency": "EUR",
            "direction": "out",
            "recurrence": null,
            "status": "open",
            "snoozed_until": null,
            "priority": "normal",
            "area": "study",
            "party_id": "pty_library",
            "case_id": null,
            "contract_id": null,
            "doc_id": "doc_library",
            "evidence": [
              {
                "doc_id": "doc_library",
                "page": 1,
                "quote": "Bitte geben Sie die Medien zurück und begleichen Sie die Gebühr von 4,50 EUR bis zum 02.10.2026.",
                "grounding": "verified",
                "value_consistent": true,
                "score": 0.97,
                "boxes": [
                  {
                    "page": 1,
                    "x0": 0.1185,
                    "y0": 0.4442,
                    "x1": 0.8226,
                    "y1": 0.4585
                  },
                  {
                    "page": 1,
                    "x0": 0.1185,
                    "y0": 0.4636,
                    "x1": 0.2171,
                    "y1": 0.4779
                  }
                ]
              }
            ],
            "grounding": "verified",
            "slot_key": "slot_itm_library_fee",
            "user_modified": false,
            "due_date_source": "fixed",
            "origin": "extracted",
            "location": null,
            "filed_on": null,
            "created_at": "2026-09-26T07:49:00Z",
            "updated_at": "2026-09-26T07:49:00Z",
            "completed_at": null
          }
        },
        {
          "key": "item:itm_rent_oct",
          "ref": {
            "type": "item",
            "id": "itm_rent_oct"
          },
          "title": "Rent for October",
          "kind": "payment",
          "date": "2026-10-05",
          "date_role": "pay_by",
          "due_date": null,
          "amount": 640.0,
          "currency": "EUR",
          "party_id": "pty_wohnbau",
          "party_name": "Wohnbau Musterstadt eG",
          "doc_id": "doc_lease",
          "status": "open",
          "note": null,
          "tone": "neutral",
          "overdue": false,
          "item": {
            "id": "itm_rent_oct",
            "kind": "payment",
            "title": "Rent for October",
            "description": null,
            "action": null,
            "consequence": null,
            "due_date": "2026-10-05",
            "due_time": null,
            "send_by": null,
            "date_spec": {
              "type": "relative",
              "date": null,
              "time": null,
              "anchor": "explicit_date",
              "anchor_date": "2026-10-01",
              "amount": 3,
              "unit": "werktage",
              "delivery_rule": "none",
              "shift_rule": "auto",
              "nature": "payment",
              "legal_basis": null,
              "text": "spätestens am dritten Werktag des Monats"
            },
            "computation": {
              "due_date": "2026-10-05",
              "send_by": null,
              "safe_date": null,
              "holiday_calendar": "Germany + North Rhine-Westphalia (NW)",
              "summary": "Rent is due by the 3rd working day of the month. Sat 3 Oct is a public holiday, so the 3rd working day is Mon 5 Oct.",
              "steps": [
                {
                  "label": "Month starts",
                  "date": "2026-10-01",
                  "rule_id": null,
                  "citation": null
                },
                {
                  "label": "1st working day: Thu 1 Oct",
                  "date": "2026-10-01",
                  "rule_id": "werktage",
                  "citation": null
                },
                {
                  "label": "2nd working day: Fri 2 Oct",
                  "date": "2026-10-02",
                  "rule_id": "werktage",
                  "citation": null
                },
                {
                  "label": "Sat 3 Oct is Tag der Deutschen Einheit (public holiday) — skipped",
                  "date": "2026-10-03",
                  "rule_id": "holidays_de",
                  "citation": null
                },
                {
                  "label": "3rd working day: Mon 5 Oct",
                  "date": "2026-10-05",
                  "rule_id": "bgb556b",
                  "citation": "§ 556b Abs. 1 BGB"
                }
              ],
              "rule_ids": [
                "bgb556b",
                "werktage",
                "holidays_de"
              ],
              "warnings": [],
              "confidence": "high"
            },
            "amount": 640.0,
            "currency": "EUR",
            "direction": "out",
            "recurrence": {
              "interval": 1,
              "unit": "months"
            },
            "status": "open",
            "snoozed_until": null,
            "priority": "normal",
            "area": "home",
            "party_id": "pty_wohnbau",
            "case_id": "cas_flat",
            "contract_id": null,
            "doc_id": "doc_lease",
            "evidence": [
              {
                "doc_id": "doc_lease",
                "page": 1,
                "quote": "spätestens am dritten Werktag des Monats",
                "grounding": "verified",
                "value_consistent": true,
                "score": 0.97,
                "boxes": [
                  {
                    "page": 1,
                    "x0": 0.3917,
                    "y0": 0.6255,
                    "x1": 0.7337,
                    "y1": 0.6398
                  }
                ]
              }
            ],
            "grounding": "verified",
            "slot_key": "slot_itm_rent_oct",
            "user_modified": false,
            "due_date_source": "computed",
            "origin": "extracted",
            "location": null,
            "filed_on": null,
            "created_at": "2025-09-20T18:05:00Z",
            "updated_at": "2025-09-20T18:05:00Z",
            "completed_at": null
          }
        }
      ],
      "more": 0,
      "total": 769.49,
      "total_other_currencies": {}
    },
    {
      "id": "post",
      "title": "Post and keep proof",
      "summary": "1 letter to send · 1 sent — keep the proof",
      "entries": [
        {
          "key": "draft:drf_phone",
          "ref": {
            "type": "draft",
            "id": "drf_phone"
          },
          "title": "Kündigung meines Mobilfunkvertrags – Kundennummer 7700 4412 09",
          "kind": "cancellation",
          "date": "2026-10-08",
          "date_role": "send_by",
          "due_date": "2026-10-14",
          "amount": null,
          "currency": null,
          "party_id": "pty_funknetz",
          "party_name": "FunkNetz Mobil GmbH",
          "doc_id": "doc_phone",
          "status": "draft",
          "note": "Not sent yet — send it, then mark it as sent.",
          "tone": "warn",
          "overdue": false,
          "item": null
        },
        {
          "key": "draft:drf_gym",
          "ref": {
            "type": "draft",
            "id": "drf_gym"
          },
          "title": "Kündigung meiner Mitgliedschaft „FitWell Flex“ – Mitgliedsnummer FW-20931",
          "kind": "cancellation",
          "date": "2026-09-22",
          "date_role": "sent",
          "due_date": null,
          "amount": null,
          "currency": null,
          "party_id": "pty_fitwell",
          "party_name": "FitWell Studios",
          "doc_id": "doc_gym_price",
          "status": "sent",
          "note": "Keep the posting receipt (Einlieferungsbeleg) with a copy of the letter: it proves posting, not arrival. Ask Deutsche Post for the delivery record (Auslieferungsbeleg) now — it is kept only for a limited time, and online tracking alone is no proof (BAG 2 AZR 68/24).",
          "tone": "neutral",
          "overdue": false,
          "item": null
        }
      ],
      "more": 0,
      "total": null,
      "total_other_currencies": {}
    },
    {
      "id": "waiting",
      "title": "Waiting for",
      "summary": "Waiting for 2 replies",
      "entries": [
        {
          "key": "item:itm_followup_wohnbau",
          "ref": {
            "type": "item",
            "id": "itm_followup_wohnbau"
          },
          "title": "Follow up: Wohnbau hasn't answered your request",
          "kind": "task",
          "date": "2026-10-06",
          "date_role": "reply_by",
          "due_date": null,
          "amount": null,
          "currency": null,
          "party_id": "pty_wohnbau",
          "party_name": "Wohnbau Musterstadt eG",
          "doc_id": null,
          "status": "open",
          "note": "You asked to see the receipts for the utility statement on 15 Sep. No reply yet.",
          "tone": "neutral",
          "overdue": false,
          "item": {
            "id": "itm_followup_wohnbau",
            "kind": "task",
            "title": "Follow up: Wohnbau hasn't answered your request",
            "description": "You asked to see the receipts for the utility statement on 15 Sep. No reply yet.",
            "action": "Call or email Frau Beispiel and ask for an appointment.",
            "consequence": null,
            "due_date": "2026-10-06",
            "due_time": null,
            "send_by": null,
            "date_spec": null,
            "computation": null,
            "amount": null,
            "currency": null,
            "direction": null,
            "recurrence": null,
            "status": "open",
            "snoozed_until": null,
            "priority": "normal",
            "area": "home",
            "party_id": "pty_wohnbau",
            "case_id": "cas_flat",
            "contract_id": null,
            "doc_id": null,
            "evidence": [],
            "grounding": "user",
            "slot_key": "slot_itm_followup_wohnbau",
            "user_modified": false,
            "due_date_source": "fixed",
            "origin": "draft",
            "location": null,
            "filed_on": null,
            "created_at": "2026-09-15T17:02:00Z",
            "updated_at": "2026-09-15T17:02:00Z",
            "completed_at": null
          }
        },
        {
          "key": "item:itm_followup_gym",
          "ref": {
            "type": "item",
            "id": "itm_followup_gym"
          },
          "title": "Check for a reply from FitWell Studios",
          "kind": "task",
          "date": "2026-10-13",
          "date_role": "reply_by",
          "due_date": null,
          "amount": null,
          "currency": null,
          "party_id": "pty_fitwell",
          "party_name": "FitWell Studios",
          "doc_id": "doc_gym_price",
          "status": "open",
          "note": "You sent “Kündigung meiner Mitgliedschaft „FitWell Flex“” on Tue 22 Sep 2026 (Letter by Einwurf-Einschreiben).",
          "tone": "neutral",
          "overdue": false,
          "item": {
            "id": "itm_followup_gym",
            "kind": "task",
            "title": "Check for a reply from FitWell Studios",
            "description": "You sent “Kündigung meiner Mitgliedschaft „FitWell Flex“” on Tue 22 Sep 2026 (Letter by Einwurf-Einschreiben).",
            "action": "If nothing has arrived, call them or send a short reminder — and keep a note of it.",
            "consequence": null,
            "due_date": "2026-10-13",
            "due_time": null,
            "send_by": null,
            "date_spec": null,
            "computation": null,
            "amount": null,
            "currency": null,
            "direction": null,
            "recurrence": null,
            "status": "open",
            "snoozed_until": null,
            "priority": "normal",
            "area": "leisure",
            "party_id": "pty_fitwell",
            "case_id": null,
            "contract_id": "ctr_gym",
            "doc_id": "doc_gym_price",
            "evidence": [],
            "grounding": "user",
            "slot_key": "slot_itm_followup_gym",
            "user_modified": false,
            "due_date_source": "computed",
            "origin": "draft",
            "location": null,
            "filed_on": null,
            "created_at": "2026-09-22T12:40:00Z",
            "updated_at": "2026-09-22T12:40:00Z",
            "completed_at": null
          }
        }
      ],
      "more": 0,
      "total": null,
      "total_other_currencies": {}
    },
    {
      "id": "decide",
      "title": "Decide in the next 30 days",
      "summary": "2 decisions in the next 30 days",
      "entries": [
        {
          "key": "item:itm_gym_price",
          "ref": {
            "type": "item",
            "id": "itm_gym_price"
          },
          "title": "Object to FitWell's price increase",
          "kind": "deadline",
          "date": "2026-10-06",
          "date_role": "send_by",
          "due_date": "2026-10-12",
          "amount": null,
          "currency": null,
          "party_id": "pty_fitwell",
          "party_name": "FitWell Studios",
          "doc_id": "doc_gym_price",
          "status": "open",
          "note": "Decide whether to object before then.",
          "tone": "neutral",
          "overdue": false,
          "item": {
            "id": "itm_gym_price",
            "kind": "deadline",
            "title": "Object to FitWell's price increase",
            "description": "FitWell wants to raise the monthly fee from €29.90 to €32.90 from 1 Nov.",
            "action": "If you don't agree, tell FitWell in writing (an email is enough) — or cancel with one month's notice.",
            "consequence": "FitWell says it will charge €32.90 from 1 Nov unless you object.",
            "due_date": "2026-10-12",
            "due_time": null,
            "send_by": "2026-10-06",
            "date_spec": {
              "type": "relative",
              "date": null,
              "time": null,
              "anchor": "deemed_delivery",
              "anchor_date": null,
              "amount": 4,
              "unit": "weeks",
              "delivery_rule": "de_admin_post",
              "shift_rule": "auto",
              "nature": "objection",
              "legal_basis": null,
              "text": "Sie können der Anpassung innerhalb von vier Wochen nach Zugang dieses Schreibens widersprechen."
            },
            "computation": {
              "due_date": "2026-10-12",
              "send_by": "2026-10-06",
              "safe_date": null,
              "holiday_calendar": "Germany + North Rhine-Westphalia (NW)",
              "summary": "Four weeks after the letter's date (Mon 14 Sep 2026) is Mon 12 Oct 2026.",
              "steps": [
                {
                  "label": "Not an authority's letter, so no delivery days: the period runs from the letter's date (Mon 14 Sep 2026)",
                  "date": "2026-09-14",
                  "rule_id": "private_sender_arrival",
                  "citation": "§ 130 Abs. 1 BGB"
                },
                {
                  "label": "Counting starts the day after Mon 14 Sep 2026",
                  "date": "2026-09-14",
                  "rule_id": "bgb_187_1",
                  "citation": "§ 187 Abs. 1 BGB"
                },
                {
                  "label": "Four weeks later: Mon 12 Oct 2026",
                  "date": "2026-10-12",
                  "rule_id": "bgb_188",
                  "citation": "§ 188 Abs. 2 BGB"
                },
                {
                  "label": "Mon 12 Oct 2026 is a working day, so it stays",
                  "date": "2026-10-12",
                  "rule_id": "bgb_193",
                  "citation": "§ 193 BGB"
                },
                {
                  "label": "Send by Tue 6 Oct 2026 to allow 4 business days for a letter to arrive",
                  "date": "2026-10-06",
                  "rule_id": "postal_buffer",
                  "citation": null
                }
              ],
              "rule_ids": [
                "private_sender_arrival",
                "bgb_187_1",
                "bgb_188",
                "bgb_193",
                "postal_buffer"
              ],
              "warnings": [
                "No delivery days were added: the rule that a letter counts as delivered a few days after posting is only for authorities' letters, and this sender is not an authority. The period runs from the day the letter arrived.",
                "We assumed the letter arrived on the date printed on it — tell us when it actually arrived."
              ],
              "confidence": "low"
            },
            "amount": null,
            "currency": null,
            "direction": null,
            "recurrence": null,
            "status": "open",
            "snoozed_until": null,
            "priority": "normal",
            "area": "leisure",
            "party_id": "pty_fitwell",
            "case_id": null,
            "contract_id": "ctr_gym",
            "doc_id": "doc_gym_price",
            "evidence": [
              {
                "doc_id": "doc_gym_price",
                "page": 1,
                "quote": "Sie können der Anpassung innerhalb von vier Wochen nach Zugang dieses Schreibens widersprechen.",
                "grounding": "verified",
                "value_consistent": true,
                "score": 0.97,
                "boxes": [
                  {
                    "page": 1,
                    "x0": 0.1185,
                    "y0": 0.4636,
                    "x1": 0.8098,
                    "y1": 0.4779
                  },
                  {
                    "page": 1,
                    "x0": 0.1185,
                    "y0": 0.4829,
                    "x1": 0.2437,
                    "y1": 0.4972
                  }
                ]
              }
            ],
            "grounding": "verified",
            "slot_key": "slot_itm_gym_price",
            "user_modified": false,
            "due_date_source": "computed",
            "origin": "extracted",
            "location": null,
            "filed_on": null,
            "created_at": "2026-09-15T17:03:00Z",
            "updated_at": "2026-09-15T17:03:00Z",
            "completed_at": null
          }
        },
        {
          "key": "contract:ctr_phone",
          "ref": {
            "type": "contract",
            "id": "ctr_phone"
          },
          "title": "FunkNetz Allnet L",
          "kind": "contract",
          "date": "2026-10-08",
          "date_role": "decide_by",
          "due_date": null,
          "amount": null,
          "currency": null,
          "party_id": null,
          "party_name": "FunkNetz Mobil GmbH",
          "doc_id": "doc_phone",
          "status": null,
          "note": "Renews unless you send a cancellation by then.",
          "tone": "neutral",
          "overdue": false,
          "item": null
        }
      ],
      "more": 0,
      "total": null,
      "total_other_currencies": {}
    },
    {
      "id": "file",
      "title": "File or archive",
      "summary": "Nothing to file this week",
      "entries": [],
      "more": 0,
      "total": null,
      "total_other_currencies": {}
    }
  ],
  "overdue": 0,
  "next_deadline": {
    "key": "item:itm_parking",
    "ref": {
      "type": "item",
      "id": "itm_parking"
    },
    "title": "Pay the parking fine",
    "kind": "payment",
    "date": "2026-09-29",
    "date_role": "pay_by",
    "due_date": null,
    "amount": 30.0,
    "currency": "EUR",
    "party_id": "pty_ordnungsamt",
    "party_name": "Ordnungsamt Musterstadt",
    "doc_id": "doc_parking",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": {
      "id": "itm_parking",
      "kind": "payment",
      "title": "Pay the parking fine",
      "description": "Verwarnungsgeld OA-VW-2026-55012 (Bahnhofstraße 8, 17 Sep).",
      "action": "Transfer €30 to the Stadtkasse with the reference OA-VW-2026-55012.",
      "consequence": "A formal fine procedure starts, with extra fees.",
      "due_date": "2026-09-29",
      "due_time": null,
      "send_by": null,
      "date_spec": {
        "type": "relative",
        "date": null,
        "time": null,
        "anchor": "receipt",
        "anchor_date": null,
        "amount": 1,
        "unit": "weeks",
        "delivery_rule": "none",
        "shift_rule": "auto",
        "nature": "payment",
        "legal_basis": null,
        "text": "Bitte zahlen Sie das Verwarnungsgeld innerhalb einer Woche nach Zugang dieses Schreibens."
      },
      "computation": {
        "due_date": "2026-09-29",
        "send_by": null,
        "safe_date": null,
        "holiday_calendar": "Germany + North Rhine-Westphalia (NW)",
        "summary": "The week starts when the letter reached you, which we don't know yet. Counting from the letter date (Tue 22 Sep) — the earliest possible — gives Tue 29 Sep.",
        "steps": [
          {
            "label": "Letter dated",
            "date": "2026-09-22",
            "rule_id": null,
            "citation": null
          },
          {
            "label": "Arrival date unknown — using the letter date instead (earliest possible)",
            "date": "2026-09-22",
            "rule_id": "receipt_fallback",
            "citation": null
          },
          {
            "label": "One week later",
            "date": "2026-09-29",
            "rule_id": "bgb_188",
            "citation": "§ 188 Abs. 2 BGB"
          }
        ],
        "rule_ids": [
          "receipt_fallback",
          "bgb_188"
        ],
        "warnings": [
          "Tell us when the letter arrived to get the exact date."
        ],
        "confidence": "low"
      },
      "amount": 30.0,
      "currency": "EUR",
      "direction": "out",
      "recurrence": null,
      "status": "open",
      "snoozed_until": null,
      "priority": "high",
      "area": "mobility",
      "party_id": "pty_ordnungsamt",
      "case_id": "cas_parking",
      "contract_id": null,
      "doc_id": "doc_parking",
      "evidence": [
        {
          "doc_id": "doc_parking",
          "page": 1,
          "quote": "Bitte zahlen Sie das Verwarnungsgeld innerhalb einer Woche nach Zugang dieses Schreibens.",
          "grounding": "model_read",
          "value_consistent": true,
          "score": 0.97,
          "boxes": [
            {
              "page": 1,
              "x0": 0.1615,
              "y0": 0.4472,
              "x1": 0.8263,
              "y1": 0.4599
            }
          ]
        }
      ],
      "grounding": "model_read",
      "slot_key": "slot_itm_parking",
      "user_modified": false,
      "due_date_source": "computed",
      "origin": "extracted",
      "location": null,
      "filed_on": null,
      "created_at": "2026-09-24T18:15:00Z",
      "updated_at": "2026-09-24T18:15:00Z",
      "completed_at": null
    }
  },
  "due_today": 0
};

/** Every day to act from the demo's today on, the earliest first (`week.deadlines`): the ending's
 * candidates, so it moves on to the next one when the visitor pays or closes the first. */
export const MOCK_WEEK_DEADLINES: WeekEntry[] = [
  {
    "key": "item:itm_parking",
    "ref": {
      "type": "item",
      "id": "itm_parking"
    },
    "title": "Pay the parking fine",
    "kind": "payment",
    "date": "2026-09-29",
    "date_role": "pay_by",
    "due_date": null,
    "amount": 30.0,
    "currency": "EUR",
    "party_id": "pty_ordnungsamt",
    "party_name": "Ordnungsamt Musterstadt",
    "doc_id": "doc_parking",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_tm_dunning",
    "ref": {
      "type": "item",
      "id": "itm_tm_dunning"
    },
    "title": "Pay TechMarkt reminder",
    "kind": "payment",
    "date": "2026-09-30",
    "date_role": "pay_by",
    "due_date": null,
    "amount": 94.99,
    "currency": "EUR",
    "party_id": "pty_techmarkt",
    "party_name": "TechMarkt Online GmbH",
    "doc_id": "doc_tm_dunning",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_library_fee",
    "ref": {
      "type": "item",
      "id": "itm_library_fee"
    },
    "title": "Pay library fee",
    "kind": "payment",
    "date": "2026-10-02",
    "date_role": "pay_by",
    "due_date": null,
    "amount": 4.5,
    "currency": "EUR",
    "party_id": "pty_library",
    "party_name": "Stadtbibliothek Musterstadt",
    "doc_id": "doc_library",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_library_return",
    "ref": {
      "type": "item",
      "id": "itm_library_return"
    },
    "title": "Return 2 library books",
    "kind": "task",
    "date": "2026-10-02",
    "date_role": "by",
    "due_date": null,
    "amount": null,
    "currency": null,
    "party_id": "pty_library",
    "party_name": "Stadtbibliothek Musterstadt",
    "doc_id": "doc_library",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_rent_oct",
    "ref": {
      "type": "item",
      "id": "itm_rent_oct"
    },
    "title": "Rent for October",
    "kind": "payment",
    "date": "2026-10-05",
    "date_role": "pay_by",
    "due_date": null,
    "amount": 640.0,
    "currency": "EUR",
    "party_id": "pty_wohnbau",
    "party_name": "Wohnbau Musterstadt eG",
    "doc_id": "doc_lease",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_followup_wohnbau",
    "ref": {
      "type": "item",
      "id": "itm_followup_wohnbau"
    },
    "title": "Follow up: Wohnbau hasn't answered your request",
    "kind": "task",
    "date": "2026-10-06",
    "date_role": "by",
    "due_date": null,
    "amount": null,
    "currency": null,
    "party_id": "pty_wohnbau",
    "party_name": "Wohnbau Musterstadt eG",
    "doc_id": null,
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_gym_price",
    "ref": {
      "type": "item",
      "id": "itm_gym_price"
    },
    "title": "Object to FitWell's price increase",
    "kind": "deadline",
    "date": "2026-10-06",
    "date_role": "send_by",
    "due_date": "2026-10-12",
    "amount": null,
    "currency": null,
    "party_id": "pty_fitwell",
    "party_name": "FitWell Studios",
    "doc_id": "doc_gym_price",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "contract:ctr_phone",
    "ref": {
      "type": "contract",
      "id": "ctr_phone"
    },
    "title": "FunkNetz Allnet L",
    "kind": "contract",
    "date": "2026-10-08",
    "date_role": "decide_by",
    "due_date": null,
    "amount": null,
    "currency": null,
    "party_id": null,
    "party_name": "FunkNetz Mobil GmbH",
    "doc_id": "doc_phone",
    "status": null,
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_dentist",
    "ref": {
      "type": "item",
      "id": "itm_dentist"
    },
    "title": "Dentist: check-up & cleaning",
    "kind": "appointment",
    "date": "2026-10-08",
    "date_role": "on",
    "due_date": null,
    "amount": null,
    "currency": null,
    "party_id": "pty_dentist",
    "party_name": "Zahnarztpraxis Dr. Muster",
    "doc_id": "doc_dentist",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_phone_cancel",
    "ref": {
      "type": "item",
      "id": "itm_phone_cancel"
    },
    "title": "Cancel phone contract — if you want to switch",
    "kind": "deadline",
    "date": "2026-10-08",
    "date_role": "send_by",
    "due_date": "2026-10-14",
    "amount": null,
    "currency": null,
    "party_id": "pty_funknetz",
    "party_name": "FunkNetz Mobil GmbH",
    "doc_id": "doc_phone",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_nk",
    "ref": {
      "type": "item",
      "id": "itm_nk"
    },
    "title": "Pay utility back payment (Nebenkosten)",
    "kind": "payment",
    "date": "2026-10-09",
    "date_role": "pay_by",
    "due_date": null,
    "amount": 184.3,
    "currency": "EUR",
    "party_id": "pty_wohnbau",
    "party_name": "Wohnbau Musterstadt eG",
    "doc_id": "doc_nebenkosten",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_abh_docs",
    "ref": {
      "type": "item",
      "id": "itm_abh_docs"
    },
    "title": "Prepare documents for the Ausländerbehörde",
    "kind": "task",
    "date": "2026-10-13",
    "date_role": "by",
    "due_date": null,
    "amount": null,
    "currency": null,
    "party_id": "pty_abh",
    "party_name": "Ausländerbehörde Musterstadt",
    "doc_id": "doc_abh",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_followup_gym",
    "ref": {
      "type": "item",
      "id": "itm_followup_gym"
    },
    "title": "Check for a reply from FitWell Studios",
    "kind": "task",
    "date": "2026-10-13",
    "date_role": "by",
    "due_date": null,
    "amount": null,
    "currency": null,
    "party_id": "pty_fitwell",
    "party_name": "FitWell Studios",
    "doc_id": "doc_gym_price",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_abh_appt",
    "ref": {
      "type": "item",
      "id": "itm_abh_appt"
    },
    "title": "Ausländerbehörde: extend residence permit",
    "kind": "appointment",
    "date": "2026-10-14",
    "date_role": "on",
    "due_date": null,
    "amount": null,
    "currency": null,
    "party_id": "pty_abh",
    "party_name": "Ausländerbehörde Musterstadt",
    "doc_id": "doc_abh",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_abh_fee",
    "ref": {
      "type": "item",
      "id": "itm_abh_fee"
    },
    "title": "Residence permit fee",
    "kind": "payment",
    "date": "2026-10-14",
    "date_role": "pay_by",
    "due_date": null,
    "amount": 93.0,
    "currency": "EUR",
    "party_id": "pty_abh",
    "party_name": "Ausländerbehörde Musterstadt",
    "doc_id": "doc_abh",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_bkk",
    "ref": {
      "type": "item",
      "id": "itm_bkk"
    },
    "title": "Health insurance contribution",
    "kind": "payment",
    "date": "2026-10-15",
    "date_role": "pay_by",
    "due_date": null,
    "amount": 142.86,
    "currency": "EUR",
    "party_id": "pty_bkk",
    "party_name": "Muster BKK",
    "doc_id": "doc_bkk",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_power_abschlag",
    "ref": {
      "type": "item",
      "id": "itm_power_abschlag"
    },
    "title": "Electricity instalment",
    "kind": "payment",
    "date": "2026-10-15",
    "date_role": "pay_by",
    "due_date": null,
    "amount": 48.0,
    "currency": "EUR",
    "party_id": "pty_stadtwerke",
    "party_name": "Stadtwerke Musterstadt",
    "doc_id": "doc_power",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_rundfunk",
    "ref": {
      "type": "item",
      "id": "itm_rundfunk"
    },
    "title": "Broadcasting fee Oct–Dec",
    "kind": "payment",
    "date": "2026-11-15",
    "date_role": "pay_by",
    "due_date": null,
    "amount": 55.08,
    "currency": "EUR",
    "party_id": "pty_beitrag",
    "party_name": "Beitragsservice Musterstadt",
    "doc_id": "doc_rundfunk",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_bank_decide",
    "ref": {
      "type": "item",
      "id": "itm_bank_decide"
    },
    "title": "Decide on Musterbank's new account fee",
    "kind": "task",
    "date": "2026-11-30",
    "date_role": "by",
    "due_date": null,
    "amount": null,
    "currency": null,
    "party_id": "pty_musterbank",
    "party_name": "Musterbank AG",
    "doc_id": "doc_bank",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_liability",
    "ref": {
      "type": "item",
      "id": "itm_liability"
    },
    "title": "Liability insurance (yearly)",
    "kind": "payment",
    "date": "2026-12-01",
    "date_role": "pay_by",
    "due_date": null,
    "amount": 59.9,
    "currency": "EUR",
    "party_id": "pty_versicherung",
    "party_name": "Muster Versicherung AG",
    "doc_id": "doc_liability",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_scholarship",
    "ref": {
      "type": "item",
      "id": "itm_scholarship"
    },
    "title": "Submit scholarship progress report",
    "kind": "deadline",
    "date": "2026-12-15",
    "date_role": "due",
    "due_date": null,
    "amount": null,
    "currency": null,
    "party_id": "pty_scholarship",
    "party_name": "Global Futures Scholarship Programme",
    "doc_id": "doc_scholarship",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  },
  {
    "key": "item:itm_semester",
    "ref": {
      "type": "item",
      "id": "itm_semester"
    },
    "title": "Semester fee summer 2027",
    "kind": "payment",
    "date": "2027-01-15",
    "date_role": "pay_by",
    "due_date": null,
    "amount": 312.4,
    "currency": "EUR",
    "party_id": "pty_hochschule",
    "party_name": "Hochschule Musterstadt",
    "doc_id": "doc_uni",
    "status": "open",
    "note": null,
    "tone": "neutral",
    "overdue": false,
    "item": null
  }
];
