"""HTTP routes, one module per resource (SPEC §13). :data:`ROUTERS` are mounted under ``/api``."""

from __future__ import annotations

from fastapi import APIRouter

from ordnung.api.routes import (
    ask,
    backup,
    brief,
    calendar,
    calendar_sync,
    cases,
    contracts,
    data,
    demo,
    documents,
    drafts,
    events,
    export,
    folder,
    girocode,
    items,
    numbers,
    overview,
    parties,
    phone,
    privacy,
    profile,
    proofs,
    reminders,
    suggestions,
    sync,
    system,
    traces,
    waiting,
    week,
)

ROUTERS: tuple[APIRouter, ...] = (
    system.router,
    profile.router,
    data.router,
    privacy.router,
    documents.router,
    export.router,
    folder.router,
    traces.router,
    items.router,
    girocode.router,
    contracts.router,
    parties.router,
    cases.router,
    overview.router,
    numbers.router,
    week.router,
    suggestions.router,
    brief.router,
    ask.router,
    drafts.router,
    proofs.router,
    waiting.router,
    calendar.router,
    calendar_sync.router,
    reminders.router,
    backup.router,
    phone.router,
    sync.router,
    events.router,
    demo.router,
)
