/**
 * The static demo's GiroCodes (generated by scripts/gen_mock_girocodes.py from the real gate) match
 * the mock world they describe: every payment has one, each code carries its letter's payment
 * details and its to-do's amount, a value called "found in the text layer" is printed on the mock
 * letter, a photo-read one comes from a photo — and "These match the letter" behaves like the API.
 */
import { describe, expect, it } from "vitest";
import type { DocumentDetail, GiroCode, TransferValues } from "@/api/types";
import { normalizeIban } from "@/lib/format";
import { readPayload } from "@/features/girocode/qr";
import { GIROCODE_REFUSALS, GIROCODES, GIROCODES_CHECKED } from "./data/girocodes";
import { ITEMS, TRAY_ITEMS } from "./data/items";
import { letterFor } from "./db";
import { amountText } from "./girocode";
import { createMockServer } from "./server";

const PAYMENTS = [...ITEMS, ...Object.values(TRAY_ITEMS).flat()].filter((i) => i.kind === "payment");
const PARKING: TransferValues = { payee: "Stadtkasse Musterstadt", iban: "DE51123456000000100017", reference: "OA-VW-2026-55012", amount: 30 };

function server() {
  const srv = createMockServer({ staticDemo: true, latency: 0 });
  srv.openAllMail();
  return srv;
}

const compact = (text: string) => text.replace(/[^\p{L}\p{N}]+/gu, "").toUpperCase();

/** Every page of a mock letter as one string of letters and digits. */
function printed(docId: string): string {
  const letter = letterFor(docId);
  if (!letter) return "";
  return compact(letter.pages.map((_, i) => letter.pageText(i + 1)).join(" "));
}

describe("the demo's codes describe the mock world", () => {
  it("every payment of the demo has its code (or its reason) and nothing else does", () => {
    expect(Object.keys(GIROCODES).sort()).toEqual(PAYMENTS.map((i) => i.id).sort());
  });

  it("each code carries its letter's payment details and its to-do's amount", () => {
    const srv = server();
    for (const code of [...Object.values(GIROCODES), ...Object.values(GIROCODES_CHECKED)]) {
      const item = PAYMENTS.find((i) => i.id === code.item_id)!;
      const pay = srv.db.document(item.doc_id!)!.payment;
      const values: TransferValues | null =
        code.status === "ready" ? { ...readPayload(code.payload), payee: readPayload(code.payload).name } : code.values;
      if (code.status === "blocked" && code.reason === "no_iban") {
        expect(pay?.iban ?? null, code.item_id).toBeNull();
        continue;
      }
      if (!values) continue; // settled or scam: no values to compare
      expect(values.payee, code.item_id).toBe(pay!.payee);
      expect(normalizeIban(values.iban ?? ""), code.item_id).toBe(pay!.iban);
      expect(values.reference, code.item_id).toBe(pay!.reference);
      expect(values.amount, code.item_id).toBe(item.amount);
    }
  });

  it("what counts as printed on the letter is printed there; what was read from a photo is a photo", () => {
    const srv = server();
    for (const code of Object.values(GIROCODES) as GiroCode[]) {
      if (code.status === "blocked" && code.reason !== "check_letter") continue;
      const item = PAYMENTS.find((i) => i.id === code.item_id)!;
      const doc = srv.db.document(item.doc_id!)!;
      const toCheck = code.status === "blocked" ? code.to_check : [];
      const text = printed(doc.id);
      if (doc.text_mode === "vision") {
        expect(toCheck, code.item_id).toEqual(["amount", "iban", "reference"]);
        continue;
      }
      if (!toCheck.includes("iban")) expect(text, `${code.item_id}: IBAN on the letter`).toContain(compact(doc.payment!.iban!));
      if (!toCheck.includes("reference")) expect(text, `${code.item_id}: reference on the letter`).toContain(compact(doc.payment!.reference!));
      if (!toCheck.includes("amount")) {
        const cents = item.amount!.toFixed(2).replace(".", ",");
        expect(item.evidence.some((e) => e.quote.includes(cents)), `${code.item_id}: amount in its sentence`).toBe(true);
      }
    }
  });
});

describe("“These match the letter” in the demo", () => {
  const confirm = (srv: ReturnType<typeof server>, id: string, values: TransferValues) =>
    srv.handle("POST", `/items/${id}/girocode/confirm`, new URLSearchParams(), values);
  const detail = async (srv: ReturnType<typeof server>, id: string) =>
    (await (await srv.handle("GET", `/documents/${id}`, new URLSearchParams(), undefined)).json()) as DocumentDetail;

  it("unlocks the parking fine's code, logs it, and forgets it on marking it paid", async () => {
    const srv = server();
    expect((await detail(srv, "doc_parking")).girocodes).toEqual([GIROCODES.itm_parking]);
    const res = await confirm(srv, "itm_parking", { ...PARKING, iban: "de51 1234 5600 0000 1000 17" });
    expect(res.status).toBe(200);
    expect(await res.json()).toEqual(GIROCODES_CHECKED.itm_parking);
    expect((await detail(srv, "doc_parking")).girocodes).toEqual([GIROCODES_CHECKED.itm_parking]);
    expect(srv.db.state.activity[0]).toMatchObject({ kind: "payment.checked", ref_type: "item", ref_id: "itm_parking" });

    await srv.handle("PATCH", "/items/itm_parking", new URLSearchParams(), { status: "done" });
    expect((await detail(srv, "doc_parking")).girocodes[0]).toMatchObject({ status: "blocked", reason: "settled", message: "No code: you marked this as paid." });
  });

  it("asks for the paper letter again when a code's amount was changed, then carries the new amount", async () => {
    const srv = server();
    const patch = (id: string, amount: number) => srv.handle("PATCH", `/items/${id}`, new URLSearchParams(), { amount });
    // a code from the letter's text layer: the new amount isn't the letter's
    await patch("itm_nk", 190);
    const [asks] = (await detail(srv, "doc_nebenkosten")).girocodes;
    expect(asks).toMatchObject({ status: "blocked", reason: "check_letter", to_check: ["amount"], message: "No code yet: the amount wasn't found in the letter's text. Compare it with the paper letter, then confirm." });
    const values = (asks as Extract<GiroCode, { status: "blocked" }>).values!;
    expect(values).toEqual({ payee: "Wohnbau Musterstadt eG", iban: "DE05123456000004455660", reference: "MV-2025-0412 NK 2025", amount: 190 });
    await confirm(srv, "itm_nk", { ...values, amount: 184.3 }).then((res) => expect(res.status).toBe(409));
    const res = await confirm(srv, "itm_nk", values);
    expect(res.status).toBe(200);
    const ready = (await res.json()) as GiroCode;
    expect(ready).toEqual({ status: "ready", item_id: "itm_nk", checked: true, payload: (GIROCODES.itm_nk as Extract<GiroCode, { status: "ready" }>).payload.replace("EUR184.3", "EUR190") });
    // back to the letter's amount: the letter's own code
    await patch("itm_nk", 184.3);
    expect((await detail(srv, "doc_nebenkosten")).girocodes).toEqual([GIROCODES.itm_nk]);

    // a photo's code compared at €30 no longer covers €35
    await confirm(srv, "itm_parking", PARKING);
    await patch("itm_parking", 35);
    const [again] = (await detail(srv, "doc_parking")).girocodes;
    expect(again).toMatchObject({ status: "blocked", reason: "check_letter", to_check: ["amount", "iban", "reference"], values: { ...PARKING, amount: 35 } });
    expect((await (await confirm(srv, "itm_parking", { ...PARKING, amount: 35 })).json()).payload).toContain("\nEUR35\n");
  });

  it("writes amounts as the payload builder does", () => {
    expect([30, 184.3, 184.35, 100, 0.1, 1000.5].map(amountText)).toEqual(["EUR30", "EUR184.3", "EUR184.35", "EUR100", "EUR0.1", "EUR1000.5"]);
  });

  it("refuses other values, a ready code, a scam and unknown to-dos, like the API", async () => {
    const srv = server();
    const refused = async (id: string, values: TransferValues, status: number, detailText: string) => {
      const res = await confirm(srv, id, values);
      expect(res.status, id).toBe(status);
      expect(((await res.json()) as { detail: string }).detail).toBe(detailText);
    };
    await refused("itm_parking", { ...PARKING, amount: 35 }, 409, GIROCODE_REFUSALS.changed);
    await refused("itm_nk", PARKING, 409, GIROCODE_REFUSALS.nothing_to_compare);
    const scam = GIROCODES.itm_scam_demand;
    await refused("itm_scam_demand", PARKING, 409, scam.status === "blocked" ? scam.message : "");
    await refused("itm_bank_decide", PARKING, 409, GIROCODE_REFUSALS.not_a_payment);
    await refused("itm_nope", PARKING, 404, "Unknown to-do.");
    expect(srv.db.state.activity.some((a) => a.kind === "payment.checked")).toBe(false);
  });

  it("files the scam letter's demand apart in its sender's drawer, never as something to do", async () => {
    const srv = server();
    const party = (await (await srv.handle("GET", "/parties/pty_beitrag", new URLSearchParams(), undefined)).json()) as { set_aside: { item_id: string; reason: string }[] };
    expect(party.set_aside).toContainEqual({ item_id: "itm_scam_demand", reason: "suspicious", replaced_by: null });
    const dashboard = (await (await srv.handle("GET", "/dashboard", new URLSearchParams(), undefined)).json()) as { attention: { id: string }[]; upcoming: { id: string }[] };
    expect([...dashboard.attention, ...dashboard.upcoming].map((i) => i.id)).not.toContain("itm_scam_demand");
  });
});
