/**
 * The static demo's My numbers and weekly session. Both are computed by Ordnung's own Python code over
 * the mock letters (`data/numbers.ts`, generated by `scripts/gen_mock_numbers.py`); here they only follow
 * what the visitor does: a letter deleted in the demo takes its numbers along, a to-do marked done leaves
 * its step, and "Finish" / "Not now" are remembered for this mock database.
 */
import type { CallSheet, MyNumber, MyNumbers, OpenCase, WeekEntry, WeekStep, WeeklySession } from "@/api/types";
import type { MockDb } from "./db";
import { MOCK_NUMBERS, MOCK_WEEK } from "./data/numbers";

interface WeekState {
  lastSession: string | null;
  dismissed: string | null;
}

const weekStates = new WeakMap<MockDb, WeekState>();

function stateOf(db: MockDb): WeekState {
  let state = weekStates.get(db);
  if (!state) {
    state = { lastSession: null, dismissed: null };
    weekStates.set(db, state);
  }
  return state;
}

const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v)) as T;

/** My numbers of the letters still in the demo. */
export function mockNumbers(db: MockDb): MyNumbers {
  const live = new Set(db.liveDocuments().map((d) => d.id));
  const shown = (n: MyNumber | null | undefined): n is MyNumber => Boolean(n && (!n.letter || live.has(n.letter.id)));
  const openCase = (c: OpenCase): OpenCase | null => {
    const references = c.references.filter(shown);
    return references.length && (!c.letter || live.has(c.letter.id)) ? { ...c, references } : null;
  };
  const data = clone(MOCK_NUMBERS);
  const cases = data.open_cases.map(openCase).filter((c): c is OpenCase => c !== null);
  const sheets = data.organisations
    .map((s): CallSheet => ({
      ...s,
      numbers: s.numbers.filter(shown),
      their_numbers: s.their_numbers.filter(shown),
      open_cases: s.open_cases.map(openCase).filter((c): c is OpenCase => c !== null),
      last_letter: s.last_letter && live.has(s.last_letter.id) ? s.last_letter : null,
    }))
    .filter((s) => s.numbers.length || s.open_cases.length);
  return {
    ...data,
    about_you: data.about_you.filter(shown),
    documents: data.documents
      .filter((d) => !d.letter || live.has(d.letter.id))
      .map((d) => ({ ...d, number: shown(d.number) ? d.number : null })),
    organisations: sheets,
    open_cases: cases,
  };
}

/** Whether a row still stands in the demo: its letter kept, its to-do still open, its draft there. */
function stillThere(db: MockDb, entry: WeekEntry): boolean {
  if (entry.doc_id && !db.document(entry.doc_id)) return false;
  switch (entry.ref.type) {
    case "document":
      return Boolean(db.document(entry.ref.id));
    case "item": {
      const item = db.state.items.find((i) => i.id === entry.ref.id);
      if (!item) return false;
      return entry.date_role === "done" ? item.status === "done" : item.status === "open" || item.status === "snoozed";
    }
    case "contract":
      return db.state.contracts.some((c) => c.id === entry.ref.id && c.status === "active");
    case "draft":
      return db.state.drafts.some((d) => d.id === entry.ref.id && (entry.date_role === "sent" || d.status !== "sent"));
    default:
      return true;
  }
}

function followStep(db: MockDb, step: WeekStep): WeekStep {
  const entries = step.entries.filter((e) => stillThere(db, e));
  if (entries.length === step.entries.length) return step;
  const total = step.id === "pay" ? entries.reduce((sum, e) => sum + (e.date_role !== "collected" && (e.currency ?? "EUR") === "EUR" ? (e.amount ?? 0) : 0), 0) : step.total;
  return {
    ...step,
    entries,
    total: step.total === null ? null : Math.round((total ?? 0) * 100) / 100,
    summary: entries.length || step.more ? `${entries.length + step.more} left to look at` : "All done here",
  };
}

/** The weekly session as it stands in the demo. */
export function mockWeek(db: MockDb): WeeklySession {
  const week = clone(MOCK_WEEK);
  const state = stateOf(db);
  const steps = week.steps.map((s) => followStep(db, s));
  const next = week.next_deadline && stillThere(db, week.next_deadline) ? week.next_deadline : null;
  return {
    ...week,
    steps,
    next_deadline: next,
    last_session: state.lastSession,
    // "Finish" or "Not now" today: no prompt until a week on (the demo's today doesn't move)
    due: !state.lastSession && !state.dismissed && steps.some((s) => s.entries.length > 0),
  };
}

export function mockWeekDone(db: MockDb): WeeklySession {
  stateOf(db).lastSession = db.today;
  db.log("week.done", "Weekly session done");
  return mockWeek(db);
}

export function mockWeekDismiss(db: MockDb): WeeklySession {
  stateOf(db).dismissed = db.today;
  return mockWeek(db);
}
