"""Write the static demo's "get advice" cards from the real rules (``web/src/mocks/data/advice.ts``).

The hosted demo runs on hand-written mocks without the backend; its cards must still say exactly what
the rules engine says. Run after changing :mod:`ordnung.rules.advice`::

    .venv/bin/python scripts/gen_mock_advice.py > web/src/mocks/data/advice.ts
"""

from __future__ import annotations

import json
from datetime import date

from ordnung.models import HIGH_STAKES_KINDS
from ordnung.rules.advice import letter_advice

#: The mock demo's "today" (web/src/mocks/data/constants.ts).
TODAY = date(2026, 9, 28)
#: Sam's operating-cost statement in the mock demo (web/src/mocks/data/documents.ts: doc_nebenkosten).
STATEMENT_TEXT = "Abrechnungszeitraum 01.10.2025 bis 31.12.2025"


def main() -> None:
    by_kind = {kind: letter_advice(kind, today=TODAY) for kind in HIGH_STAKES_KINDS}
    # once the person entered the arrival (delivery) day, the cards stop asking for it
    arrived = {
        kind: letter_advice(kind, today=TODAY, arrived=TODAY, arrival_confirmed=True)
        for kind in HIGH_STAKES_KINDS
    }
    statement = letter_advice(
        "operating_costs",
        today=TODAY,
        arrived=date(2026, 9, 11),
        arrival_confirmed=True,
        region="NW",
        text=STATEMENT_TEXT,
    )

    def dump(value: object) -> str:
        return json.dumps(value, ensure_ascii=False, indent=2)

    print("// Generated by scripts/gen_mock_advice.py from the real rules — do not edit by hand.")
    print('import type { HighStakesKind, LetterAdvice } from "@/api/types";')
    print()
    print(
        "/** The card each high-stakes kind carries (facts computed without a letter's amounts or text). */"
    )
    kinds = {kind: card.model_dump() for kind, card in by_kind.items() if card is not None}
    print(f"export const ADVICE_BY_KIND: Record<HighStakesKind, LetterAdvice> = {dump(kinds)};")
    print()
    print("/** The same cards once the person entered when the letter arrived (or was delivered). */")
    confirmed = {kind: card.model_dump() for kind, card in arrived.items() if card is not None}
    print(f"export const ADVICE_ARRIVED_BY_KIND: Record<HighStakesKind, LetterAdvice> = {dump(confirmed)};")
    print()
    print(
        "/** Cards worked out from a demo letter itself (Sam's operating-cost statement), while it is filed as "
        "it was read. */"
    )
    docs = {"doc_nebenkosten": statement.model_dump() if statement else None}
    print(f"export const ADVICE_BY_DOC: Record<string, LetterAdvice> = {dump(docs)};")


if __name__ == "__main__":
    main()
