"""Write the static demo's high-stakes letters' dates from the real rules (``web/src/mocks/data/highStakes.ts``).

The hosted demo runs on hand-written mocks without the backend. Two of its New-mail letters are
high-stakes letters (a Mahnbescheid and a dismissal); their dates, receipts and warnings — and how
to send the objection the law gives such letters — must be exactly what the rules engine says, so
this script computes them. Run after changing
:mod:`ordnung.rules`::

    .venv/bin/python scripts/gen_mock_high_stakes.py > web/src/mocks/data/highStakes.ts
"""

from __future__ import annotations

import json
from datetime import date, timedelta

from ordnung.drafts.compose import STATUTORY_OBJECTION_NOTES
from ordnung.models import DateSpec
from ordnung.rules import send_guidance
from ordnung.rules.deadlines import RuleContext, compute_due
from ordnung.rules.routing import derived_deadlines

#: The mock demo's "today" (web/src/mocks/data/constants.ts) and Sam's Land.
TODAY = date(2026, 9, 28)
REGION = "NW"

#: web/src/mocks/data/letters.ts: doc_mahnbescheid (dated Wed 23 Sep, envelope date unknown).
ORDER_DATE = date(2026, 9, 23)
ORDER_SPEC = DateSpec(
    type="relative",
    anchor="receipt",
    amount=2,
    unit="weeks",
    nature="objection",
    text="binnen zwei Wochen seit der Zustellung dieses Bescheids",
)
#: doc_dismissal: dated Fri 25 Sep, received today, the job ends on Sat 31 Oct 2026.
DISMISSAL_DATE = date(2026, 9, 25)
JOB_END = date(2026, 10, 31)


def _order(received: date | None) -> dict[str, object]:
    ctx = RuleContext(
        today=TODAY,
        region=REGION,
        document_date=ORDER_DATE,
        received_date=received,
        received_confirmed=received is not None,
        letter_kind="court_payment_order",
    )
    return compute_due(ORDER_SPEC, ctx).model_dump()


def main() -> None:
    order = {"unknown": _order(None)}
    day = ORDER_DATE
    while day <= TODAY:  # every envelope date the arrival question accepts
        order[day.isoformat()] = _order(day)
        day += timedelta(days=1)
    ctx = RuleContext(
        today=TODAY,
        region=REGION,
        document_date=DISMISSAL_DATE,
        received_date=TODAY,
        received_confirmed=True,
        letter_kind="dismissal",
        end_date=JOB_END,
    )
    dismissal = {
        entry.rule_id: {
            "spec": entry.spec.model_dump(),
            "receipt": compute_due(entry.spec, ctx).model_dump(),
            "title": entry.title,
            "action": entry.action,
            "consequence": entry.consequence,
            "priority": entry.priority,
        }
        for entry in derived_deadlines("dismissal", end=JOB_END)
    }

    def dump(value: object) -> str:
        return json.dumps(value, ensure_ascii=False, indent=2)

    objections = {}
    for kind in ("court_payment_order", "enforcement_order", "landlord_notice"):
        guidance = send_guidance("objection", letter_kind=kind, today=TODAY)
        # as compose._notes: a written-form letter's form note, then what the objection does
        notes = [guidance.form_note] if guidance.form == "written_form" and guidance.form_note else []
        notes.extend([STATUTORY_OBJECTION_NOTES[kind]] if kind in STATUTORY_OBJECTION_NOTES else [])
        objections[kind] = {"guidance": guidance.model_dump(), "notes": notes}

    print("// Generated by scripts/gen_mock_high_stakes.py from the real rules — do not edit by hand.")
    print('import type { ComputationReceipt, DateSpec, Priority, SendGuidance } from "@/api/types";')
    print()
    print("/** The Mahnbescheid's objection deadline: unknown envelope date, and each date Sam may enter. */")
    print(f"export const ORDER_RECEIPTS: Record<string, ComputationReceipt> = {dump(order)};")
    print()
    print('/** The deadlines the law adds to the dismissal (to-dos with origin "rule"). */')
    print(
        "export const DISMISSAL_RULES: Record<string, { spec: DateSpec; receipt: ComputationReceipt; title: string; "
        f"action: string; consequence: string; priority: Priority }}> = {dump(dismissal)};"
    )
    print()
    print(
        "/** How to send the objection the law gives a court order or a landlord's notice (dates added per letter). */"
    )
    print(
        "export const STATUTORY_OBJECTIONS: Record<string, { guidance: SendGuidance; notes: string[] }> = "
        f"{dump(objections)};"
    )


if __name__ == "__main__":
    main()
